<?php
if (file_exists(dirname(dirname(dirname(dirname(dirname(__FILE__))))).'/wp-load.php')) {
	require_once(dirname(dirname(dirname(dirname(dirname(__FILE__))))).'/wp-load.php'); // WP 2.6+
} else {
	require_once(dirname(dirname(dirname(dirname(dirname(__FILE__))))).'/wp-config.php'); // WP 2.5
}
@header('Content-type: text/css' );

/* include default static css for theme preview */
if (!function_exists('p2_option')) {
	include('../images/activate.css');
} ?>
/* do not edit this file, it is generated by the theme, any edits will be lost  */
<?php
// let's set some variables
$url 			= p2_imageurl( 'bouquet1', false ); 
$headerlayout 	= p2_option( 'headerlayout', 0 );
$logow 			= p2_imagewidth( 'logo', 0 );
$logoh 			= p2_imageheight( 'logo', 0 );
$commentslayout = p2_option( 'commentslayout', 0 );
$theme_path		= get_bloginfo( 'template_directory');

// variables set conditionally
$opacity = p2_option( 'nav_dropdown_opacity', 0 );
if ( ( $opacity > 99 ) || ( $opacity < 1 ) ) {
	$opacity = '';
} 
// calculate the width
$width			= p2_option( 'blog_width', 0 ); 
//echo "/* width: $width */";
if ( p2_test( 'blog_border', 'border' ) ) $width = $width - ( p2_option('blog_border_width', 0 ) * 2 );
if ( p2_test( 'blog_border', 'dropshadow' ) ) $width = $width - 14;
?>
/* ---------------------- */
/* ----GENERAL STUFF----- */
/* ---------------------- */
body {
	background:<?php p2_option( 'bg_color' ); ?> url(<?php p2_imageurl( 'blog_bg' ); ?>) <?php p2_option( 'bg_img_position' );?>;
	color:<?php p2_option( 'gen_font_color' ); ?>;
	font-family:<?php p2_option( 'gen_font_family' ); ?>;
	text-transform:<?php p2_option( 'gen_text_transform' ); ?>; 
}
<?php font_css( 'gen', 'p' ); ?>
<?php link_css( 'gen', '' ); ?>
<?php 
// headlines throughout, applies overall headline styles, can be overriden below
font_css( 'header', 'h2' ); 
font_css( 'header', 'h3' );
font_css( 'header', 'body.single h1.entry-title', true ); ?>



/* ---------------------- */
/* -----OTHER PAGES------ */
/* ---------------------- */
<?php font_css( 'archive_h2', 'h2.page-title' ); ?>
.archive-meta {
	margin-bottom:<?php echo p2_option( 'archive_h2_margin_below', 0 ) * 1.3; ?>px;
	margin-right: 220px;
	font-style: italic !important;
}



/* ---------------------- */
/* -------FOOTER--------- */
/* ---------------------- */
#sidebar-footer {
	background:<?php p2_option( 'footer_bg_color' ) ?>;
	padding:50px 10px 24px <?php echo $tmp = $width / 14.5; ?>px;
	color:<?php p2_option( 'footer_nonlink_font_color' ); ?>;
	line-height:1.4em !important;
}
#sidebar-footer p {
	color:<?php p2_option( 'footer_nonlink_font_color' ); ?>;
}
#primary, #secondary, #tertiary {
	float:left;
	width:32%;
	font-size:<?php p2_option( 'footer_link_font_size' ) ?>px;
}
.top-level-sidebar {
	width:<?php echo $tmp = $width / 4.81; ?>px;
	margin:0 auto;
}
<?php font_css( 'footer_headings', '#sidebar-footer h3' ); ?>
#sidebar-footer li {
	margin-bottom:<?php p2_option( 'footer_widget_margin_below' ); ?>px;
}
#sidebar-footer li li {
	margin-bottom:2px;
	margin-left:10px;
	line-height:1.2em;
}
<?php link_css( 'footer', '#sidebar-footer ' ); ?>
#footer {
	text-align:center;
	background:<?php p2_option( 'body_bg_color' ) ?>;
	padding-bottom:8px;
}
#footer p {
	color:<?php p2_option( 'gen_font_color' ); ?>;
	font-size:11px;
	margin-top:13px;
<?php if ( p2_test( 'footer_include', 'no' ) ) echo "\tpadding-top:20px;\n"; ?>
	margin-bottom:0;
}



/* ---------------------- */
/* -----LAYOUT STUFF----- */
/* ---------------------- */
<?php 
// styles for subtle dropshadow blog bg image
if ( p2_option( 'blog_border', 0 ) == 'dropshadow' ) { ?>#outerwrapper {
	width: <?php p2_option( 'blog_width' ); ?>px;
	margin:0 auto;
	background: url(<?php echo $theme_path; ?>/images/dropshadow<?php p2_option( 'blog_width' ) ?>.png) repeat-y;
}
* html #outerwrapper {
	background-image:none !important;
}<?php }  // end dropshadow ?> 
#wrapper {
	background:<?php p2_option( 'body_bg_color' ); ?>;
	width:<?php echo $width; ?>px; 
	margin:<?php p2_option( 'blog_top_margin' ); ?>px auto <?php p2_option( 'blog_top_margin' ); ?>px auto;<?php 
	// blog border styles
	if ( p2_option( 'blog_border', 0 ) == 'border' ) { echo "\n\t"; ?>border:solid <?php p2_option( 'blog_border_width' ); ?>px <?php p2_option( 'blog_border_color' ); ?>;<?php if ( p2_option( 'blog_border_topbottom', 0 ) == 'no' ) echo "\n\tborder-top-width:0;\n\tborder-bottom-width:0;"; } ?> 
}
#header {
	background:<?php p2_option( 'header_bg_color' ); ?>;
}
<?php
// calculate content margin
$content_margin = 31;
if ( p2_test( 'inner_margin', 'zero' ) ) $content_margin = 0;
?>
#content {
	padding-left:<?php echo $content_margin; ?>px; 
	padding-right:<?php echo $content_margin; ?>px; 
}



/* ---------------------- */
/* ---NAVIGATION MENU---- */
/* ---------------------- */
#topnav {
	background: <?php p2_option( 'nav_bg_color' ); // nav background color ?>;
<?php 
	// overall padding for nav menu
		// if dropshadow
	if ( p2_option( 'blog_border', 0 ) == 'dropshadow' ) echo "\tpadding-left:18px;\n\tpadding-right:18px;\n"; 
	
		// if extra custom padding added
	if ( p2_option( 'nav_center_padding', 0 ) ) { 
		echo "\tpadding-left:" . p2_option( 'nav_center_padding', 0 ) . "px;\n"; 
		// or if standard border
	} else if ( p2_option( 'blog_border', 0 ) == 'border' ) { 
		echo "\tpadding-left:";
			// cacluate it based on font-size
		echo $tmp = ( p2_option( 'nav_top_fontsize', 0 ) / 1.4 );
		echo "px;\n";
	}

	// float it right, if that option is chosen
	if ( p2_option( 'nav_align', 0 ) == 'right' ) echo "\tfloat:right;\n";	
	
		// custom border line above
		if ( p2_option( 'nav_border_top', 0 ) == 'on' ) {
			echo "\tborder-top:" . p2_option( 'nav_border_top_width', 0 ) . 'px ' . p2_option( 'nav_border_top_style', 0 ) . " " . p2_option( 'nav_border_top_color', 0 ) . ";\n";
		}
		// custom border line below
		if ( p2_option( 'nav_border_bottom', 0 ) == 'on' ) {
			echo "\tborder-bottom:" . p2_option( 'nav_border_bottom_width', 0 ) . 'px ' . p2_option( 'nav_border_bottom_style', 0 ) . " " .  p2_option( 'nav_border_bottom_color', 0 ) . ";\n";
		}
?>
}
#topnav {
	line-height:<?php p2_option( 'nav_top_fontsize' ); ?>px; 
	font-size:<?php p2_option( 'nav_top_fontsize' ); ?>px;
}
#topnav li {
	margin-right: <?php 
	// calculate padding between nav links
		// default is a multiplier of font size
	$navr_pad = p2_option( 'nav_top_fontsize', 0 ) * 1.8; 
		// unless overridden by custom option
	if ( p2_option( 'nav_link_padding_right', 0 ) ) $navr_pad = p2_option( 'nav_link_padding_right', 0 );
	echo $navr_pad;
	?>px;
	<?php 
	// top and bottom padding of nav link
		// default is 10px
	$tb_pad = 10;
		// unless font size is smaller than 14px, then do some math
	if ( p2_option( 'nav_top_fontsize', 0 ) < 14 ) $tb_pad = p2_option( 'nav_top_fontsize', 0 ) / 1.4;
		// but, if small font & search is in dopdown, then math is different
		// because we don't have to account for height of search form
	if ( ( p2_option( 'nav_top_fontsize', 0 ) < 14 ) && ( ( p2_option( 'nav_search_dropdown', 0 ) == 'off' ) && p2_option( 'navsearchonoff', 0 ) == 'on' ) ) $tb_pad = ( 32 - p2_option( 'nav_top_fontsize', 0 ) ) / 2; ?>
padding-top: <?php echo $tb_pad; ?>px;
	padding-bottom: <?php echo $tb_pad; ?>px; 
}
#topnav li ul {
	margin-top:<?php echo $tb_pad; ?>px; 
	background: <?php p2_option( 'nav_bg_color' ); ?> !important;
	<?php if ( p2_is_bound( 'nav_dropdown_bg_color' ) ) { ?>background: <?php p2_option( 'nav_dropdown_bg_color' ); ?> !important;<?php } ?>
}
#topnav ul li {
	background: <?php p2_option( 'nav_bg_color' ); ?>;
	<?php if ( p2_is_bound( 'nav_dropdown_bg_color' ) ) { ?>background: <?php p2_option( 'nav_dropdown_bg_color' ); ?> !important;<?php } ?>
	line-height: <?php echo $tmp = p2_option( 'nav_dropdown_link_textsize', 0) * 1.5  ?>px;
}
li#search-top ul {
	background: <?php p2_option( 'nav_bg_color' ); ?>;
	<?php if ( p2_is_bound( 'nav_dropdown_bg_color' ) ) { ?>background: <?php p2_option( 'nav_dropdown_bg_color' ); ?> !important;<?php } ?>
}
#topnav li li,
<?php if ( p2_option( 'nav_search_dropdown', 0 ) == 'off' ) echo "#topnav li#search-top,\n"; ?>
#topnav li#subscribebyemail-nav {
	padding-bottom:0;
}
<?php if ( p2_option( 'nav_search_dropdown', 0 ) == 'off' ) echo "#topnav li#search-top,\n"; ?>#topnav li#subscribebyemail-nav {
	padding-top:<?php
	// calculate the top padding to keep search vertically centered
	$nav_height = p2_option( 'nav_top_fontsize', 0 ) + ( $tb_pad * 2);
	$padding = ( ( $nav_height - 23) / 2);
	if ( ( p2_option( 'nav_search_dropdown', 0 ) == 'off' ) && ( $padding < 4) ) $padding = 4;
	echo $padding;
	?>px;
}
<?php link_css( 'nav', '#topnav ' ); ?>
#topnav a {
	font-size:<?php p2_option('nav_top_fontsize')?>px;
}
#topnav li li a {
	font-size:<?php p2_option( 'nav_dropdown_link_textsize' ); ?>px;
}
#topnav li ul a:hover {
	background:<?php p2_option( 'nav_dropdown_bg_hover_color' ); ?>; 
}
<?php // IF search area on right of nav menu
if ( p2_option( 'navsearchleftright', 0 ) == 'right' ) { ?>#topnav li#search-top {
	float:right;
	margin-right:<?php echo $tmp = ( p2_option( 'nav_top_fontsize', 0 ) / 1.4 ); ?>px;
	padding-right:0;
}
<?php } // END IF search area on right of nav menu ?>
<?php // IF subscribe by email form is on right
if ( p2_option( 'subscribebyemail_nav_leftright', 0 ) == 'right' ) { ?>#topnav li#subscribebyemail-nav {
	float:right;
	margin: 0 0 0 20px;
}
<?php }// END IF subscribe by email form is on right ?>
#topnav-outer {
	background: <?php p2_option( 'nav_bg_color' ); ?>;
}
<?php // IF nav menu RSS link is on
if ( p2_option( 'nav_rss', 0 ) == 'on' ) { ?>
li#nav-rss a#nav-rss-subscribe {
	<?php if ( p2_test( 'nav_rss_use_icon', 'yes' ) ) { ?>padding-left:<?php echo $tmp = p2_option( 'nav_top_fontsize', 0 ) / 2; ?>px;<?php } ?> 
}
<?php } // END IF nav menu RSS link is on ?>
<?php // IF twitter integration on
if ( p2_option( 'twitter_onoff', 0 ) == 'on' ) { ?>
	
	
	
/* ---------------------- */
/* -------TWITTER ------- */
/* ---------------------- */
#topnav #twitter-nav li {
	padding:5px 8px 3px 8px;
	width:114px;
	font-size:<?php p2_option( 'nav_dropdown_link_textsize' ); ?>px;
	color:<?php p2_option( 'nav_link_visited_font_color' ); ?>;
}
#topnav #twitter-nav li a {
	padding-left:0;
}
#topnav #twitter-nav li:hover {
	background:<?php p2_option( 'nav_dropdown_bg_hover_color' ); ?>;
}
#twitter_update_list span {
	color:<?php p2_option( 'nav_link_font_color' ) ?>; 
}<?php } // END IF twitter integration on ?>



/* ---------------------- */
/* ------POST ----------- */
/* ---------------------- */
<?php // this allows the post/page titles to inherit the general header styles ?>
h2.entry-title a, 
h3.entry-title a {
	font-size:<?php p2_option( 'header_font_size' ); ?>px; 
	color:<?php p2_option( 'header_font_color' ); ?>;
	font-family:<?php p2_option( 'header_font_family' ); ?>;
	text-transform:<?php p2_option( 'header_text_transform' ); ?>;
	font-style:<?php p2_option( 'header_font_style' ); ?>;
}
h2.entry-title a:link, 
h3.entry-title a:link {
	color:<?php p2_option( 'header_font_color' ); ?>;
}	
<?php // IF post title link font color is not set
if ( !p2_is_bound( 'post_title_link_font_color' ) ) { ?>h2.entry-title a:visited, 
h3.entry-title a:visited {
	color:<?php p2_option( 'header_font_color' ); ?>;
}
h2.entry-title a:hover, 
h3.entry-title a:hover {
	color:<?php p2_option( 'header_font_color' ); ?>;
}<?php } // END IF post title link font color is not set ?> 
<?php // override general header styles by more specific styling
	  link_css( 'post_title', 'h2.entry-title ', false, true ); ?>
<?php link_css( 'post_title', 'h3.entry-title ', false, true ); ?>
body.single h1.entry-title,
body.page h1.entry-title {
<?php font_css( 'header' ); ?>
	<?php font_css( 'post_title', '', true); ?>
	<?php font_css( 'single_h1' ); ?> 
}
h2.entry-title,
h3.entry-title,
h1.entry-title {
	margin-bottom: <?php p2_option( 'post_title_margin_below' ); ?>px;
}
<?php font_css( 'emt', '.entry-meta-top p' ); ?>
.entry-meta-top p a:link, 
.entry-meta-top p a:visited, 
.entry-meta-top p a:hover {
	text-transform:<?php p2_option( 'emt_text_transform' ); ?>;
	font-style:<?php p2_option( 'emt_font_style' ); ?> 
}
.entry-meta-bottom a:link, 
.entry-meta-bottom a:visited, 
.entry-meta-bottom a:hover {
	text-transform:<?php p2_option( 'emb_text_transform' ); ?>;
	font-style:<?php p2_option( 'emb_font_style' ); ?> 
}
<?php font_css( 'emb', '.entry-meta-bottom p' ); ?>
<?php link_css( 'em', '.entry-meta ' ); ?>
<?php font_css( 'post_text', '.entry-content p', false, true ); ?>
.entry-content li {
	font-size:<?php p2_option( 'gen_font_size' ); ?>px;
	line-height:<?php echo $tmp = p2_option( 'gen_line_height', 0 ) * .85; ?>em;
	margin-bottom: 1em;
	margin-left: 3em;
}
.entry-content img, .entry-content .gallery img {
	border:none;
<?php // post picture borders
	if ( p2_option( 'post_pic_border_width', 0 ) ) {
		echo "\tborder:solid " . p2_option( 'post_pic_border_width', 0 ) . 'px ' . p2_option( 'post_pic_border_color', 0 ) . ";\n";
	}?>	margin-top:<?php p2_option( 'post_pic_margin_top' ); ?>px;
	margin-bottom:<?php p2_option( 'post_pic_margin_bottom' ); ?>px;
}
.entry-title, .entry-meta-top {
	text-align:<?php p2_option( 'post_header_align' ); ?>;
}
.posted-in {
	<?php 
	// if categories on the same line wih post date/time
	if ( ( p2_option( 'cat_header_placement', 0 ) == 'same' )
		&& 
	// and categories in top meta area
	( p2_option( 'cattopbottom', 0 ) == 'top' ) )  {
		// then style appropriately
		echo 'margin-left:';
		if ( p2_option( 'emt_link_font_size', 0 ) ) { 
			$emt_size = ( p2_option( 'emt_link_font_size', 0 ) * 1.1 );
		} else {
			$emt_size = ( p2_option( 'gen_font_size', 0 ) * 1.1 ); 
		}
		echo $emt_size;
		echo "px;\n"; 
	} else {
		// else, force it onto it's own line
		 echo "display:block;\n"; 
	} font_css( 'cat' ); ?>
}
<?php link_css( 'cat_link', '.posted-in ' ); ?>
<?php // IF post titles have border underneath 
if ( p2_option( 'post_header_border', 0 ) == 'on' ) { ?>
.entry-meta-top {
	border-bottom:<?php p2_option( 'post_header_border_width' ); ?>px <?php p2_option( 'post_header_border_style' ); ?> <?php p2_option( 'post_header_border_color' ); ?>;
	padding-bottom:<?php p2_option( 'post_header_border_padding' ); ?>px !important;
	margin-bottom:<?php p2_option( 'post_header_border_margin' ); ?>px !important;
}	
<?php } // END IF post titles have border underneath ?>
.entry-post {
	<?php if ( !p2_test( 'post_divider_onoff', 'none') ) { ?>margin-bottom:<?php p2_option( 'margin_below_post' ); ?>px;<?php } ?>
	<?php // if there is no post-divider, style: 
	if ( p2_option( 'post_divider_onoff', 0 ) == 'none' ) echo "padding-bottom:" . p2_option( 'padding_below_post', 0 ) . "px;\n"; ?>
<?php // if post divider is a line
	if ( p2_option( 'post_divider_onoff', 0 ) == 'line' ) {
		echo "padding-bottom:" . p2_option( 'padding_below_post', 0 ) . "px;\n\t";
		echo "border-bottom:";
		p2_option( 'post_sep_border_width' );
		echo "px ";
		p2_option( 'post_sep_border_style' );
		echo " ";
		p2_option( 'post_sep_border_color' );
		echo ";\n";
	} 
	// if post divider is an image
	if ( ( p2_option( 'post_divider_onoff', 0 ) == 'image' ) && p2_image_exists( 'post_sep' ) ) {
		echo "background: url(";
		p2_imageurl( 'post_sep' );
		echo ") no-repeat bottom center;\n\t";
		echo "padding-bottom:";
		echo $post_sep_padding = ( p2_imageheight( 'post_sep', 0 ) + p2_option( 'padding_below_post', 0 ) );
		echo "px;\n";
	}
	?>
}
<?php // IF post divider on archive pages is set same as home page
if ( p2_option( 'archive_post_divider', 0 ) == 'same' ) { ?>body.archive .entry-post {
	<?php if ( !p2_test( 'post_divider_onoff', 'none') ) { ?>margin-bottom:<?php p2_option( 'margin_below_post' ); ?>px;<?php } ?>
	<?php // if no divider set for home page
	if ( p2_option( 'post_divider_onoff', 0 ) == 'none' ) echo "padding-bottom:" . p2_option( 'padding_below_post', 0 ) . "px;\n"; ?>
<?php  // if divider line is inherited from home page
	if ( p2_option( 'post_divider_onoff', 0 ) == 'line' ) {
		$padding_bottom = p2_option( 'padding_below_post', 0 ) - p2_option( 'gen_margin_below', 0 );
		echo "padding-bottom:" . $padding_bottom . "px;\n";
		echo "\tborder-bottom:";
		p2_option( 'post_sep_border_width' );
		echo "px ";
		p2_option( 'post_sep_border_style' );
		echo " ";
		p2_option( 'post_sep_border_color' );
		echo ";\n";
	} 
	// if divider image is inherited from home page
	if ( ( p2_option( 'post_divider_onoff', 0 ) == 'image' ) && p2_image_exists( 'post_sep' ) ) {
		echo "background: url(";
		p2_imageurl( 'post_sep' );
		echo ") no-repeat bottom center;\n\t";
		echo "padding-bottom:";
		echo $post_sep_padding = ( p2_imageheight( 'post_sep', 0 ) + p2_option( 'padding_below_post', 0 ) ) - p2_option( 'gen_margin_below', 0 );
		echo "px;\n";
	} ?>
}
<?php } // END IF post divider on archive pages is same as home page ?>
<?php // IF there is a unique archive-page post divider line set
if ( p2_option( 'archive_post_divider', 0 ) == 'line' ) { ?>body.archive .entry-post {
	margin-bottom:<?php p2_option( 'archive_margin_below_post' ); ?>px;
<?php
	echo "padding-bottom:" . p2_option( 'archive_padding_below_post', 0 ) . "px;\n";
	echo "border-bottom:";
	p2_option( 'archive_post_sep_border_width' );
	echo "px ";
	p2_option( 'archive_post_sep_border_style' );
	echo " ";
	p2_option( 'archive_post_sep_border_color' );
	echo ";\nbackground-image:none;\n";
?>	
}<?php } // END IF there is a unique archive-page post divider line set?>
.entry-content {
	margin-top:<?php p2_option( 'post_header_margin_below' ) ?>px;
}
blockquote {
	border-left: 1px dotted <?php
	// pick the right color for th blockquote left border line detail
	if ( p2_test( 'post_text_font_color' ) ) : p2_option( 'post_text_font_color' );
	else : p2_option( 'gen_font_color' );
	endif; ?>;
}
<?php if ( p2_test( 'post_divider_onoff', 'image' ) ) { ?>
body.home .protected {
	padding-bottom: <?php p2_imageheight( 'post_sep' ); ?>px;
}
body.home .permitted {
	padding-bottom: <?php echo $post_sep_padding = ( p2_imageheight( 'post_sep', 0 ) + p2_option( 'padding_below_post', 0 ) ); ?>px;
}
<?php } ?>


/* ---------------------- */
/* ----CONTACT FORM------ */
/* ---------------------- */
#p2-contact-success {
	background: <?php p2_option( 'contact_success_bg_color' ); ?>;
	color: <?php p2_option( 'contact_success_text_color' ); ?>;
}
#p2-contact-error {
	background: <?php p2_option( 'contact_error_bg_color' ); ?>;
	color: <?php p2_option( 'contact_error_text_color' ); ?>;
}
<?php // optional contact area override colors below 
if ( p2_option( 'contact_bg_color', 0 ) ) { ?>#contact-form {
	background: <?php p2_option( 'contact_bg_color' ); ?>;
}<?php } ?>
<?php if ( p2_option( 'contact_text_color', 0 ) ) { ?>
#contact-form p {
	color: <?php p2_option( 'contact_text_color' ); ?>;
}<?php } ?>
<?php if ( p2_option( 'contact_header_color', 0 ) ) { ?>
#contact-form h2 {
	color: <?php p2_option( 'contact_header_color' ); ?>;
}<?php } ?>



/* ---------------------- */
/* ------BIO AREA-------- */
/* ---------------------- */
<?php // bio area calculations
$badge_width	= 176;
if ( p2_test( 'bio_twitter', 'interact' ) ) $badge_width = 290;
$biomargins		= 40; // this may end up being user input
$picleftright	= p2_option( 'biopicleftright', 0 );
// width of bio picture
if ( p2_test( 'biopiconoff', 'off' ) ) {
	$biopicw 	= 0;
} else {
	$biopicw 	= p2_imagewidth( 'biopic1', 0 );
}
// calculate the width of the #biocolumns
$border = p2_option( 'biopic_border_width', 0 );
if ( p2_test( 'biopiconoff', 'off' ) ) $border = 0;
$biotextwidth = $width - $biopicw - ( $border * 2 );
// add the correct number of margin chunks
if ( $biopicw != 0 ) {
	$margins = $biomargins * 3;
} else {
	$margins = $biomargins * 2;
};
$biotextwidth = $biotextwidth - $margins;
// add some if we're stripping out the inner margins
if ( p2_test( 'inner_margin', 'zero' ) ) {
	$biotextwidth = $biotextwidth + 80;
}
// text column width 
if ( p2_test( 'bio2column', 'on' ) ) {
	$column_width = ( ( $biotextwidth - $biomargins ) / 2) - 1;
	if ( ! p2_test( 'bio_twitter', 'off' ) ) {
		$column_width = ( ( $biotextwidth - ( $biomargins * 2 ) - $badge_width ) / 2) - 1;
	}
} else { // one column but twitter is included
	if ( ! p2_test( 'bio_twitter', 'off' ) ) {
		$column_width = $biotextwidth - $biomargins - $badge_width;
	}
}

 ?>
<?php font_css( 'bio_header', '#bio h2' ); ?>
<?php font_css( 'bio_para', '#bio p' ); ?>
<?php // IF default bio bg images, or just gradient, or color
if ( ( p2_option( 'bio_bg', 0 ) == 'default' ) || p2_option( 'bio_bg', 0 ) == 'gradient' ) { ?>
#bio-outer {
	background: #FFFFFF url(<?php echo $theme_path; ?>/images/bio-gradient.jpg) repeat-x bottom left;
}
div#bio {
	<?php // if bio bottom border line set
	if ( p2_option( 'bio_border', 0 ) == 'border' ) { ?>border-bottom:<?php p2_option( 'bio_border_thickness' ); ?>px <?php p2_option( 'bio_border_style' ); ?> <?php p2_option( 'bio_border_color' ); ?>;<?php } ?>
	<?php // if bio is minimized, start it out hidden 
	if ( p2_option( 'use_hidden_bio', 0 ) == 'yes' ) echo "display:none;" ?>
}
<?php // (nested) IF bio bg option is default, i.e, also has "page-turn" image:
if ( p2_option( 'bio_bg', 0 ) == 'default' ) { ?>#bio-inner {
	background: url(<?php echo $theme_path; ?>/images/bio-pageturn<?php if ( $picleftright == 'right' ) echo '-alt'; ?>.jpg) no-repeat top <?php if ( $picleftright == 'left' ) echo 'right'; else echo 'left'?>;
}
<?php } // (nested) END IF bio bg option is default, i.e, also has "page-turn" image ?>
<?php // ELSE IF default bio bg images, or just gradient, color selected
	} elseif ( ( p2_option( 'bio_bg', 0 ) == 'color' ) ) { ?>
#bio-outer {
	background: <?php p2_option( 'bio_bg_color' ); ?>;
}
<?php } // END IF, ELSEIF default bio bg images, or just gradient, color selected ?>
div#bio {
	<?php if ( p2_option( 'use_hidden_bio', 0 ) == 'yes' ) echo "display:none;" ?>
}
<?php // IF there is a bio border line, and background option is not default, or image
if ( ( p2_option( 'bio_border', 0 ) == 'border' ) && ( p2_option( 'bio_bg', 0 ) != 'default' ) ) { ?>
#bio-outer {
	border-bottom:<?php p2_option( 'bio_border_thickness' ); ?>px <?php p2_option( 'bio_border_style' ); ?> <?php p2_option( 'bio_border_color' ); ?>;
}
<?php // ELSE IF there is a bio border line, and background option is not default, or image
} elseif ( p2_option( 'bio_border', 0 ) == 'image' ) { ?>
#bio-separator {
	background-image:url(<?php p2_imageurl( 'bio_separator' ); ?>);
	background-position: bottom center;
	background-repeat: no-repeat;
	height:<?php p2_imageheight( 'bio_separator' ); ?>px;
}	
<?php } // END IF there is a bio border line, and background option is not default, or image?>
img#biopic {
	float:<?php echo $picleftright; ?>;
	<?php 
	// biopic on left side
	if ( $picleftright == 'left' ) {
		echo "margin: " . $biomargins . "px 0 0 " . $biomargins . "px;\n\t"; 
	// biopic on right
	} else {
		echo "margin: " . $biomargins . "px " . $biomargins . "px 0 0;\n";	
	}?>
border:<?php p2_option( 'biopic_border_width' ); ?>px solid <?php p2_option( 'biopic_border_color' ); ?>;
	display:inline;
}
#biocolumns {
	display:inline;
	
	<?php 
	// if bio pic is right, float the text content left
	if ( $picleftright == "right") { 
		echo "float:left;\n\tmargin:" . $biomargins . "px " . $biomargins . "px 0 " . $biomargins . "px;\n"; 
	// or vice-versa
	} else { 
		echo "float:right;\n\tmargin:" . $biomargins . "px " . $biomargins . "px 0 " . $biomargins . "px;\n"; 
	}; ?>
	width:<?php echo $biotextwidth;	?>px;
}
<?php // the actual bio columns divs
// IF two colmumns
if ( p2_test( 'bio2column', 'on' ) || ! p2_test( 'bio_twitter', 'off' ) ) { ?>
.biocolumn {
	width:<?php echo $column_width; ?>px;
	float:left;
	display:inline;
} 
#biocolumn1 {
	margin-right:<?php echo $biomargins; ?>px;
}<?php } // END IF two colmumns ?>
<?php if ( ! p2_test( 'bio_twitter', 'off' ) ) { ?>
#twitter-badge {
	width:176px;
	float:left;
	display:inline
}
#biocolumn2 {
	margin-right:<?php echo $biomargins; ?>px;
}
#biocolumn1 {
	margin-right:<?php echo $biomargins; ?>px;
}
<?php } ?>	
<?php // IF there is a bio signature image
if ( p2_image_exists( 'bio_signature' ) ) { ?>
#bio-signature {
	float:<?php p2_option( 'bio_sig_float' ); ?>;
	clear:both;
	margin: <?php p2_option( 'bio_sig_top_margin' ); echo 'px '; p2_option( 'bio_sig_right_margin' ); echo 'px 0 '; p2_option( 'bio_sig_left_margin' ); ?>px; 
}	
<?php } // END IF there is a bio signature image ?>



/* ---------------------- */
/* ----HEADER LAYOUT----- */
/* ---------------------- */
<?php // IF prophoto classic solid colored top bar on 
if ( p2_test( 'prophoto_classic_bar', 'on' ) ) { ?>
#top-colored-bar {
	height:<?php p2_option( 'prophoto_classic_bar_height' ); ?>px;
	background: <?php p2_option( 'prophoto_classic_bar_color' ); ?>;
}	
<?php } // END IF prophoto classic solid colored top bar on?>
#logo {
<?php
//position the logo area according to layout
switch( $headerlayout ) {
case "defaultc":
	$left = ( $width / 2) - ( $logow / 2);
	echo '	position:absolute;
	top:0;
	left:' . $left . 'px;';
	break;
case "defaultr":
	echo '	position:absolute;
	top:0;
	right:0;';
	break;
case "default":
	echo '	position:absolute;
	top:0;
	left:0;';
	break;
default:
	break;
	}	
	?>
	width:<?php echo $logow; ?>px;
	height:<?php echo $logoh; ?>px;
	overflow:hidden;
<?php
//position the logo area according to layout
switch( $headerlayout ) {	
	case 'default':
	case 'defaultr':
	case 'defaultc':
	case 'pptclassic':
		echo '';
		break;
	case 'logobelowa':
	case 'logobelowb':
	case 'logotopa':
	case 'logotopb':
		echo "float:none;\n\tmargin:0 auto;\n";
		break;
	case 'logobelowal':
	case 'logobelowbl':
	case 'logotopal':
	case 'logotopbl':
		echo "float:none;\n\tmargin:0;\n";
		break;
	case 'logobelowar':
	case 'logobelowbr':
	case 'logotopar':
	case 'logotopbr':
		$margin = $width - $logow;
		echo "float:none;\n\tmargin:0 0 0 " . $margin . "px;\n";
		break;
	default:
		echo '';
} ?>
}
#logoimg {
	position:absolute;
	top:0;
	left:0;
	z-index:50;
}
#flash-header-wrapper {
	height:<?php p2_imageheight( 'flashheader1' ) ?>px;
}
#flash-header {
<?php 
// position the flash header according to header layout
switch( $headerlayout ) {
	case "default":
		$tmp = $width - $logow;
		echo '	width:' . $tmp . 'px;';
		echo "\n\tposition:absolute;\n\ttop:0;\n\tleft:" . $logow . "px;";
		break;
	case "defaultc":
		echo '	width:' . $width . 'px;\n';
		echo "	float:none;";
		break;
	case "defaultr":
		$tmp = $width - $logow;
		echo '	width:' . $tmp . 'px;';
		break;
	case "logotopa":
	case "logotopb":
	case "logobelowa":
	case "logobelowb":
	case "pptclassic":
		echo '	width:' . $width . 'px;';
		echo '	float:none;';
		break;
	default:
		echo '	width:' . $width . 'px;';
		echo '	float:none;';
		break;
} ?>
	height:<?php 
	switch( $headerlayout ) {
		case "default":
		case "defaultc":
		case "defaultr":
			echo $logoh;
			break;
		default:
			p2_imageheight( 'flashheader1' );
	} ?>px;
	overflow:hidden;	
}
#masthead {
	<?php switch ( $headerlayout ) {
		case "default":
		case "defaultc":
		case "defaultr":
		case "defaultl":
		case "pptclassic":
			echo "position:relative;";
			break;
		default:
			echo "";
		} ?>
<?php // height of layout set by logo for certain cases
if ( ( $headerlayout == "default") || ( $headerlayout == "defaultr") || ( $headerlayout == "defaultc") ) echo "\theight:" . $logoh . "px;\n"; ?>
<?php
// custom border line above
if ( p2_option( 'masthead_border_top', 0 ) == 'on' && $headerlayout != 'pptclassic' ) {
	echo "border-top:" . p2_option( 'masthead_border_top_width', 0 ) . 'px ' . p2_option( 'masthead_border_top_style', 0 ) . " " . p2_option( 'masthead_border_top_color', 0 ) . ";\n";
}
// custom border line below
if ( p2_option( 'masthead_border_bottom', 0 ) == 'on' && $headerlayout != 'pptclassic' ) {
	echo "border-bottom:" . p2_option( 'masthead_border_bottom_width', 0 ) . 'px ' . p2_option( 'masthead_border_bottom_style', 0 ) . " " .  p2_option( 'masthead_border_bottom_color', 0 ) . ";\n";
}
?>
}
<?php // ppt_classic layout special styles
if ( $headerlayout == "pptclassic") {	?>
#topnav {
	float:left;
	display:inline;
	position:absolute;
	bottom:3px;
	right:0;
}
#topnav li#search-top {
	float:left;
	display:inline;
}
#flash-header-wrapper {
<?php // custom border line above
if ( p2_option( 'masthead_border_top', 0 ) == 'on' ) {
	echo "border-top:" . p2_option( 'masthead_border_top_width', 0 ) . 'px ' . p2_option( 'masthead_border_top_style', 0 ) . " " . p2_option( 'masthead_border_top_color', 0 ) . ";\n";
}
// custom border line below
if ( p2_option( 'masthead_border_bottom', 0 ) == 'on' ) {
	echo "border-bottom:" . p2_option( 'masthead_border_bottom_width', 0 ) . 'px ' . p2_option( 'masthead_border_bottom_style', 0 ) . " " .  p2_option( 'masthead_border_bottom_color', 0 ) . ";\n";
} ?>
}
<?php } ?>



/* ---------------------- */
/* -------COMMENTS------- */
/* ---------------------- */
.comment-time {
<?php // if comment time aligned right, float it there
if ( p2_option( 'commenttime', 0 ) == 'right' ) echo "\tfloat:right;\n"; ?>
	color:<?php p2_option( 'commenttimecolor' ); ?>;
	margin:0 0 0 10px;
}
<?php // comments non-alt, non-byauthor styling below ?>
.comments-body p, 
.comments-body p a {
	<?php if ( p2_test('comments_link_font_size', 0 ) ) { ?>font-size:<?php p2_option('comments_link_font_size') ?>px;<?php } ?>  
	<?php if ( p2_test('comments_link_font_size', 0 ) ) { ?>font-family:<?php p2_option('comments_link_font_family') ?>;<?php } ?>  
	<?php if ( p2_test('comments_link_font_style', 0 ) ) { ?>font-style:<?php p2_option('comments_link_font_style') ?>;<?php } ?>  
	<?php if ( p2_test('comments_link_text_transform', 0 ) ) { ?>text-transform:<?php p2_option('comments_link_text_transform') ?>;<?php } ?>  
}
.comments-body p {
	<?php if ( p2_is_bound('comments_nonlink_font_color', 0 ) ) { ?>color:<?php p2_option('comments_nonlink_font_color') ?>;<?php } ?> 
}
.comments-body p span.comment-author,
.comments-body p.alt span.comment-author,
.comments-body p a:link,
.comments-body p.alt a:link,
.comments-body p a:visited,
.comments-body p.alt a:visited,
.comments-body p a:hover,
.comments-body p.alt a:hover {
	color: <?php p2_option( 'gen_link_font_color' ); ?>; 
	<?php if ( p2_is_bound('comments_link_font_color', 0 ) ) { ?>color:<?php p2_option('comments_link_font_color') ?>;<?php } ?> 
}
.comments-body p a:link,
.comments-body p.alt a:link,
.comments-body p a:visited,
.comments-body p.alt a:visited {
	<?php if ( p2_test('comments_link_decoration', 0 ) ) { ?>text-decoration:<?php p2_option('comments_link_decoration') ?>;<?php } ?> 
}
.comments-body p a:hover,
.comments-body p.alt a:hover {
	<?php if ( p2_test('comments_link_hover_decoration', 0 ) ) { ?>text-decoration:<?php p2_option('comments_link_hover_decoration') ?>;<?php } ?> 
}
<?php // comment alt timestamps styles below
if ( p2_is_bound( 'comments_timestamp_alt_color' ) ) { ?>.alt .comment-time {
	color:<?php p2_option( 'comments_timestamp_alt_color' ); ?>;
}<?php } ?>
<?php if ( p2_is_bound( 'comments_timestamp_byauthor_color' ) ) { ?>.entry-comments .bypostauthor .comment-time {
	color:<?php p2_option( 'comments_timestamp_byauthor_color' ); ?>;
}<?php } ?>
<?php link_css( 'comments_header', '.comments-header p ', true, true ); ?>
.comment {
	background: <?php p2_option( 'comments_comment_bg' ); echo ';';
	// if comment border chosen, style it
	if ( p2_option( 'comments_comment_border_onoff', 0 ) == 'on' ) {
		echo "\n\tborder-bottom:"; 
		p2_option( 'comments_comment_border_style' );
		echo ' ';
		p2_option( 'comments_comment_border_thickness' );
		echo 'px ';
		p2_option( 'comments_comment_border_color' );
	} ?>;
}
<?php // style alternate comments
	$alt_bg = p2_option( 'comments_comment_alt_bg', 0 );
	$alt_color = p2_option( 'comments_comment_alt_text_color', 0 );
	$alt_timestamp_color = p2_option( 'comments_alt_timestamp_color', 0 );
	$alt_link_color = p2_option( 'comments_comment_alt_link_color', 0 ); ?>
.entry-comments .alt {
	<?php if ( p2_is_bound( 'comments_comment_alt_bg' ) ) echo "background-color: $alt_bg;" ?>
	<?php if ( p2_is_bound( 'comments_comment_alt_text_color' ) ) echo "\n\tcolor: $alt_color;" ?> 
}
<?php 
// alt timestamp, link, and link hover colors
if ( p2_is_bound( 'comments_alt_timestamp_color' ) ) { echo ".comments-body .alt .comment-time {\n\t";
	echo "color:$alt_timestamp_color;\n}\n";	
} 
if ( p2_is_bound( 'comments_comment_alt_link_color' ) ) { echo ".comments-body .alt a:link {\n\t";
	echo "color:$alt_link_color !important;\n}\n";
	echo ".comments-body .alt a:visited {\n\t";
	echo "color:$alt_link_color !important;\n}\n";	
} ?>
<?php 
// IF by post author comment styles turned on
	// grab all the options
	$byauthor_bg = p2_option( 'comments_comment_byauthor_bg', 0 );
	$byauthor_color = p2_option( 'comments_comment_byauthor_text_color', 0 );
	$byauthor_timestamp_color = p2_option( 'comments_timestamp_byauthor_color', 0 );
	$byauthor_link_color = p2_option( 'comments_comment_byauthor_link_color', 0 ); ?>
.entry-comments .bypostauthor {
	<?php if ( p2_is_bound( 'comments_comment_byauthor_bg' ) ) echo "background: $byauthor_bg;" ?>
	<?php if ( p2_is_bound( 'comments_comment_byauthor_text_color' ) ) echo "\n\tcolor: $byauthor_color;" ?>
}
<?php 
	if ( p2_is_bound( 'comments_timestamp_byauthor_color' ) ) { echo ".bypostauthor .comment-time {\n\t";
		echo "color:$byauthor_timestamp_color;\n}\n";	
	} 
	if ( p2_is_bound( 'comments_comment_byauthor_link_color' ) ) { echo ".comments-body p.bypostauthor a:link, .comments-body p.bypostauthor span.comment-author, .comments-body p.bypostauthor a:visited, .comments-body p.bypostauthor a:hover {\n\t";
		echo "color:$byauthor_link_color !important;\n}\n";	
	} ?>
<?php // comment moderation message styling
if ( p2_test( 'comments_moderation_style' ) || p2_is_bound( 'comments_moderation_color' ) ) { ?>.entry-comments .unapproved {
	<?php if ( p2_test( 'comments_moderation_style' ) ) echo 'font-style:' . p2_option( 'comments_moderation_style', 0 ) . ";"; ?> 
	<?php if ( p2_is_bound( 'comments_moderation_color' ) ) echo 'color:' . p2_option( 'comments_moderation_color', 0 ) . ";"; ?> 
}<?php } ?>
<?php if ( p2_is_bound( 'comments_moderation_alt_color' ) ) { ?>.entry-comments .alt .unapproved {
	color:<?php p2_option( 'comments_moderation_alt_color' ); ?>;
}<?php } // end comment moderation message styling ?> 
<?php 
/* BEGIN COMMENTS LAYOUT CHUNK SWITCHING */
switch( $commentslayout ) {
	// tabbed comments layout styles
	case "tabbed": ?>
.comments-body p {
	margin-bottom:0;
	line-height:1.1em;
}
.entry-comments {
	border: 1px solid #cac9c9;
	border-bottom:none;
}
.comments-header {
	background: #f4f4f4 url(<?php echo $theme_path; ?>/images/borderCAC9C9.gif) repeat-x bottom;
}
.comments-header p {
	margin-bottom:0;
	line-height:1.3em;
}
.postedby {
	float:left;
	display:inline;
	padding: 14px 16px 13px 16px;
}
.comments-count, .comments-count div {
	float:left;
	display:inline;
}
.comments-count {
	background: url(<?php echo $theme_path; ?>/images/tab1-left.jpg) no-repeat bottom left;
}
.comments-count div {
	background: url(<?php echo $theme_path; ?>/images/tab1-right.jpg) no-repeat bottom right;
}
.comments-count-active .comments-count {
	background: url(<?php echo $theme_path; ?>/images/tab2-left.jpg) no-repeat bottom left;
}
.comments-count-active .comments-count div {
	background: url(<?php echo $theme_path; ?>/images/tab2-right.jpg) no-repeat bottom right;
}
.comments-count p {
	line-height:1.3em;
	float:left;
	display:inline;
	background: none;
	padding: 13px 21px 13px 34px;
	margin:1px 0 0 0;
	background: url(<?php echo $theme_path; ?>/images/comments-closed.gif) no-repeat 21px 54%;
}
.comments-count-active .comments-count p {
	background: url(<?php echo $theme_path; ?>/images/comments-open.gif) no-repeat 21px 54%;
}
.post-interact {
	float:right;
	display:inline;
	padding:14px 14px 13px 14px;
}
.post-interact span {
	<?php 
	// if the text gets too small, make sure the bg image icons don't get clipped
	if ( p2_option( 'comments_header_link_font_size', 0 ) < 12 ) {
		$pd = ( 12 - p2_option( 'comments_header_link_font_size', 0 ) ) / 2;
	} else {
		$pd = 0;
	}
	?>
	padding-top: <?php echo $pd ?>px;
	padding-top: <?php echo $pd ?>px;
	margin-left:14px
}
.addacomment {
	background: url(<?php echo $theme_path; ?>/images/comment.gif) no-repeat left center;
	padding-left:15px
}
.emailafriend {
	background: url(<?php echo $theme_path; ?>/images/email.gif) no-repeat left center;
	padding-left:20px;
}
.linktothispost {
	background: url(<?php echo $theme_path; ?>/images/link.gif) no-repeat left center;
	padding-left:18px;
}
.comments-body {
	border-bottom:1px solid #cac9c9;
	max-height: 220px;
	overflow:auto;	
}
.comments-body-inner {
	padding:15px;
}	
.comments-body h3 {
	font-family: Georgia, serif;
	font-size: 16px;
	margin: 0 0 9px 0;
}
.comment {
	padding:.6em .7em;
}
.comment-author {
	margin-right:.2em;
}
<?php break;
	// end "tabbed comments"
	// start "boxy comments"
	case "boxy":?>
/* boxy comments */
.entry-comments .comments-header p {
	font-size: <?php echo $size = ( p2_option( 'comments_header_link_font_size', 0 ) * 1.2); ?>px !important;
}
.entry-comments .comments-header p.postedby, .entry-comments .comments-header p.postedby a, .comments-header p.post-interact a {
	font-size: <?php echo $size = ( p2_option( 'comments_header_link_font_size', 0 ) * .85); ?>px !important;
}
.comments-body h3 {
	display:none;
}
.entry-comments {
	border:solid 1px <?php p2_option( 'boxy_comments_line_color' )?>;
	height:150px;
}
.entry-comments p {
	margin-bottom:0;
}
.comments-header {
	font-size:14px;
	width:200px;
	border-right:solid 1px <?php p2_option( 'boxy_comments_line_color' )?>;
	float:left;
	height:150px !important;
	max-height:150px;
	text-align:center;
	display:table;
	#position:relative; 
	overflow:hidden;
}
* html .comments-header {
	margin-right:-3px;
}
.comments-header-inner {
	#position:absolute;
	#top: 50%;
	#left: 0;
	display:block;
	#width:200px;
	display:table-cell;
	vertical-align:middle;
}
.comments-header-inner-inner {
	#position: relative;
	#top: -50%;
}
.comments-count {
	margin:8px 0 4px 0;
}
.comments-body {
	height:137px;
	border-left:none;
	overflow:auto;
	padding:5px 8px 8px 8px;
}
.comments-body p {
	margin-bottom:0;
}
p.post-interact {
	line-height:1.2em;
}
.post-interact span a {
	padding:3px 0;
	text-decoration:none;
	display:block;
	margin:0px 30px 0 30px;
}
.comment {
	padding: 5px;
}
/* end boxy comments */
<?php break;
	// end "boxy comments"
	// start "mimimalist comments"
	case "minima": ?>
/* minima comments */
.comments-count p {
	color:<?php p2_option( 'gen_link_font_color'); ?>;
	<?php if ( p2_is_bound( 'comments_header_link_font_color' ) ) { ?>color:<?php p2_option( 'comments_header_link_font_color'); ?>;<?php } ?>
}
.comments-count p.no-comments {
	color:<?php p2_option( 'gen_font_color'); ?>;
	<?php if ( p2_is_bound( 'comments_header_nonlink_font_color' ) ) { ?>color:<?php p2_option( 'comments_header_nonlink_font_color'); ?>;<?php } ?>
}
.comments-count {
	color:<?php p2_option( 'comments_header_link_font_color' );?>;
}
.entry-comments span.hide-text {
	display:none;
}
.entry-comments span.show-text {
	display:inline;
}
.comments-count-active span.hide-text {
	display:inline !important;
}
.comments-count-active span.show-text {
	display:none !important;
}
.entry-comments p {
	margin-bottom:0;
}
.comments-header p {
	float:left;
}
.postedby {
	margin-right: 15px;
}
.comments-header p.post-interact {
	float:right;
}
.post-interact span {
	margin-left:15px;
}
.comments-body {
	max-height:190px;
	overflow:auto;
	margin:10px 0;
}
.comment {
	padding:.47em;
	line-height:1.2em;
}
/* end minima comments */
<?php } //end switch( $commentslayout ) ?>



/* ---------------------- */
/* -------MISC----------- */
/* ---------------------- */
<?php // IF hide audio player
if ( p2_test( 'audio_hidden', 'on' ) ) { ?>
#audio-player-holder {
	height:0;
	text-indent:-9999em;
}<?php } // END IF hide audio player ?> 
<?php // IF sponsors
if ( p2_test( 'sponsors', 'on' ) ) { ?>#ad-banners {
	padding:0 <?php p2_option( 'sponsors_side_margins' ); ?>px;
	text-align:center;
}
#ad-banners img {
	border:1px solid <?php p2_option( 'sponsors_border_color' ); ?>;
	margin-right:<?php p2_option( 'sponsors_img_margin_right' ); ?>px;
	margin-bottom:<?php p2_option( 'sponsors_img_margin_below' ); ?>px;
}<?php } // END IF sponsors ?>
.nav-previous {
	float:<?php p2_option( 'nav_previous_align' ); ?>;
}
.nav-next {
	float:<?php p2_option( 'nav_next_align' ); ?>;
}
<?php link_css( 'nav_below', '#nav-below ' ); ?>
/*png hack*/
img.png {
	behavior: url(<?php p2_static( 'htc' ); ?>);
}
<?php // IF inner_margin set to 0, zero out necessary margin/paddings 
if ( p2_test( 'inner_margin', 'zero' ) ) { 
	// first deal with the bio area
	if ( p2_test( 'biopiconoff', 'on' ) ) {
		echo "img#biopic {\n\tmargin-";
		if ( p2_test( 'biopicleftright', 'left' ) ) {
			echo "left:0 !important;\n}";
			echo "#biocolumns {\n\tmargin-right:0 !important;\n}";
		} else {
			echo "right:0 !important;\n}";
			echo "#biocolumns {\n\tmargin-left:0 !important;\n}";
		}
	} else {
		echo "#biocolumns {\n\tmargin-left:0 !important;\n\tmargin-right:0 !important;\n}";
	}
	// next deal with the navigation menu ?>
#topnav {
	<?php if ( ! p2_test( 'nav_center_padding' ) ) echo "padding-left:0 !important;" ?>
	padding-right:0 !important;
}
#topnav li#search-top {
	margin-right:0 !important;
}
<?php } // END if inner_margin set to 0 ?>
<?php if ( p2_test( 'override_css_switch', 'on') ) { ?>
	
	
	
/* ---------------------- */
/*- -----USER-STYLES----- */
/* ---------------------- */

<?php p2_option( 'override_css' ); } ?>	