<?php
if (file_exists(dirname(dirname(dirname(dirname(dirname(__FILE__))))).'/wp-load.php')) {
	require_once(dirname(dirname(dirname(dirname(dirname(__FILE__))))).'/wp-load.php'); // WP 2.6+
} else {
	require_once(dirname(dirname(dirname(dirname(dirname(__FILE__))))).'/wp-config.php'); // WP 2.5
}
@header('Content-type: text/xml');
?>
<!-- do not edit this file, it is created by the theme, any edits will be lost.
     Original .swf file, starting code for xml, and inspiration thanks to: 
     Marcus Grellert's Flashfader plugin - http://www.lynk.de/wordpress/flashfader/ -->
<gallery timer="<?php p2_option('flash_speed'); ?>" order="<?php p2_option('flash_order'); ?>" fadetime="<?php p2_option('flash_fadetime'); ?>" looping="<?php p2_option('flash_loop'); ?>" xpos="0" ypos="0">
<image path="<?php p2_imageurl('flashheader1'); echo "?"; echo rand( 10000, 99999 ); ?>" />

<?php
//loops through flashheader images 2-30, checks for uploaded images,
//prints additional lines as necessary
for ($counter=2; $counter<=30; $counter++) {
	$img = 'flashheader' . $counter;
	if (!strstr(p2_imageurl($img, 0), 'nodefaultimage.gif')) {
		echo "<image path=\"";
		p2_imageurl($img);
		// randomize to prevent cacheing
		echo "?";
		echo rand( 10000, 99999 ); 
		echo "\" />";
	}
}
?>
</gallery>
