<?php
if (file_exists(dirname(dirname(dirname(dirname(dirname(__FILE__))))).'/wp-load.php')) {
	require_once(dirname(dirname(dirname(dirname(dirname(__FILE__))))).'/wp-load.php'); // WP 2.6+
} else {
	require_once(dirname(dirname(dirname(dirname(dirname(__FILE__))))).'/wp-config.php'); // WP 2.5
}
@header('Content-type: text/javascript');

/* calculate width and height of flashfader */
// start with the max-width
$ff_width = p2_option( 'blog_width', 0 );
// smaller if border
if ( p2_test( 'blog_border', 'border' ) ) {
	$ff_width = $ff_width - ( p2_option( 'blog_border_width', 0 ) * 2 );
	
} else {
	$ff_width = $ff_width - 14;
}

// next the height
$ff_height = p2_imageheight( 'flashheader1', 0 );
// subtract width of logo for certain layouts, also set flashfader height for same layouts
if ( ( p2_option( 'headerlayout', 0 ) == 'default' ) || ( p2_option( 'headerlayout', 0 ) == 'defaultc' ) || ( p2_option( 'headerlayout', 0 ) == 'defaultr' ) ) { 
	$ff_width = $ff_width - p2_imagewidth( 'logo', 0 );
	$ff_height = p2_imageheight( 'logo', 0 );
}



?>// do not edit this file, it is created by the theme, any edits will be lost

<?php if ( p2_test( 'contactform_yesno', 'yes' ) ) { ?>
	<?php if ( p2_test( 'contactform_ajax', 'on' ) )  { ?>
// throb text "loading message" for (hopefully) long enough to load contact form
function p2_throb() {
	jQuery('#contact-throbber').fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1).fadeTo(200, .5).fadeTo(200, 1);
}


// Load if needed (ajax) and toggle contact form display
function p2_toggle_contactform(delay) {
	if (delay == undefined) delay = 500;
	var a = jQuery('#p2-contact-click').html();
	jQuery('#p2-contact-click a').remove();
	jQuery("<a id='contact-throbber'><?php p2_sanitizer('contactform_loading_text', true, true); ?></a>").appendTo('#p2-contact-click');
	p2_throb();
	jQuery('#contact-form').load('<?php echo get_bloginfo('template_directory').'/includes/contact.php'; ?>', function(){
		jQuery('#p2-contact-click a').remove();
		jQuery(a).appendTo('#p2-contact-click');
		jQuery('#contact-form').slideToggle(delay);
		p2_contactform_loaded = true;
		jQuery('#referpage').val(window.location); // update hidden field location with page URL
		jQuery('#p2-nav-contact').unbind('click').click(function(){
			jQuery('#contact-form').slideToggle(500);
		})
	});
}
	<?php } else { // ajax contact form turned off ?>
function p2_toggle_contactform(delay) {
	if (delay == undefined) delay = 500;
	jQuery('#contact-form').slideToggle(delay);
}		
		
	<?php } ?>
<?php } ?>

sfHover = function() {
	var sfEls = document.getElementById("topnav").getElementsByTagName("LI");
	for (var i=0; i<sfEls.length; i++) {
		sfEls[i].onmouseover=function() {
			this.className+=" sfhover";
		}
		sfEls[i].onmouseout=function() {
			this.className=this.className.replace(new RegExp(" sfhover\\b"), "");
		}
	}
}
if (window.attachEvent) window.attachEvent("onload", sfHover); // for MSIE only


jQuery(document).ready(function(){
	<?php  // show a reminder when in under construction mode 
	if ( p2_test( 'maintenance_mode', 'on' ) ) { ?>
	jQuery('#maintenance-mode-remind').fadeTo(1000, 1, function(){
		jQuery(this).fadeOut(2000);
	});
	<?php } ?>
	
	<?php if ( p2_option( 'commentslayout', 0 ) != 'boxy' ) { ?>
	jQuery(".comments-count").click(function(){
		$thisclick = jQuery(this);
		var comments_id = "#"+$thisclick.parents(".entry-comments").attr("id");
		if ( jQuery(comments_id+" p.comment").size() > 0 ) {
			jQuery(comments_id).toggleClass('comments-count-active');
			jQuery(comments_id+" .comments-body").slideToggle(400);
		}
	});			
	<?php } ?>
	
	<?php 
	// comments show/hide quasi-link hover states
	if ( p2_test( 'commentslayout', 'minima' ) ) { 
		if ( p2_is_bound( 'comments_header_link_hover_font_color' ) ) {
			$hover_color = p2_option( 'comments_header_link_hover_font_color', 0 );
		} else if ( p2_is_bound( 'comments_header_link_font_color' ) ) {
			$hover_color = p2_option( 'comments_header_link_hover_font_color', 0 );
		} else {
			$hover_color = p2_option( 'gen_link_hover_font_color', 0 );
		}
		$decoration = false;
		if ( p2_test('comments_header_link_hover_decoration' ) ) {
			$decoration = p2_option( 'comments_header_link_hover_decoration', 0 );
		} else if ( p2_test('gen_link_hover_decoration' ) ) {
			$decoration = p2_option( 'gen_link_hover_decoration', 0 );
		}
		?> 
	jQuery('.comments-count p:not(.no-comments)').mouseover(function(){
		old_hover = jQuery(this).css('color');
		old_dec = jQuery(this).css('text-decoration');
		jQuery(this).css('color', '<?php echo $hover_color ?>');
		<?php if ( $decoration ) { ?>jQuery(this).css('text-decoration', '<?php echo $decoration ?>');<?php } ?> 
	}).mouseout(function(){
		jQuery(this).css('color', old_hover);
		<?php if ( $decoration ) { ?>jQuery(this).css('text-decoration', old_dec);<?php } ?> 
	});
	<?php } ?>

	<?php if ( p2_option( 'contactform_yesno', 0 ) == 'yes' ) { ?>	
	jQuery('#p2-nav-contact').click(function(){
		p2_toggle_contactform(500);
	});	

	var hash = window.location.hash.substr(1);
	if ( hash === 'contact-form' ) {
		p2_toggle_contactform(0);
	}
	
	// handle contact form submission messages
	if ( hash === 'error' ) {
		jQuery("#p2-contact-error")
			.css('display', 'block')
			.animate({opacity: 1.0}, 3500, function(){p2_toggle_contactform(300)})
			.fadeTo(500, 0)
			.slideUp(300);
	}
	if ( hash === 'success' ) {
		jQuery("#p2-contact-success")
			.css('display', 'block')
			.animate({opacity: 1.0}, 3500)
			.fadeTo(500, 0)
			.slideUp(300);
	}
	
	jQuery('a[href*=#contact-form]').click(function(){
		if (jQuery("#contact-form form").size() == 0 ) {
			p2_toggle_contactform();
		} else {
			jQuery('#contact-form').slideDown(500);
		}
	});
	<?php } ?>
	
	jQuery('#topnav li ul a').attr('title', '');
	
	// add arrow to dropdown with nested menu
	jQuery('#topnav li ul li:has(ul)').each(function(){
		$link = jQuery(this).children('a');
		linktext = $link.html();
		$link.html(linktext+" &raquo;");
	});
	// add underline to parent while child is being viewed
	jQuery('#topnav li ul li ul').hover(function(){
		jQuery(this).parent().children('a').css('text-decoration', 'underline');
	},function(){
		jQuery(this).parent().children('a').css('text-decoration', 'none');
	});
	
	<?php if ( p2_option('nav_dropdown_opacity', 0 ) < 100 ) { ?>
	if (!jQuery.browser.msie) {	
		jQuery('#topnav li ul').css('opacity', 0.<?php p2_option('nav_dropdown_opacity')?>);
	}
	if (jQuery.browser.msie) {
		if (jQuery('#topnav li ul li:has(ul)').size() == 0) {
			jQuery('#topnav li ul').css('opacity', 0.<?php p2_option('nav_dropdown_opacity')?>);
		}
	}
	<?php } ?>
	
	jQuery('.entry-post:last').css('border', 'none');
	var padding = jQuery('body.single .entry-content').css('padding-bottom');
	jQuery('.entry-post:last').css('padding-bottom', '0');
	jQuery('.entry-post:last').css('background-image', 'none');
	<?php if ( p2_test( 'comments_comment_border_onoff', 'on' ) ) { ?>jQuery('.comments-body-inner > p.comment:last-child').css('border', 'none');<?php } ?>
	<?php if ( p2_test( 'statcounter_code' ) ) { ?>jQuery('#statcounter-wrapper br').remove();<?php } ?>
	
	jQuery('a#hidden-bio').click(function(){
		<?php if (p2_option( 'bio_bg', 0 ) == 'default' ) { ?>jQuery('#bio-inner').css('background', 'none');<?php } ?> 
		jQuery('#bio').slideToggle(350,function(){
			jQuery('#bio-outer').css('display', 'block');
			jQuery('#biocolumns').css('display', 'inline');
			jQuery('.biocolumn').css('display', 'block');
			<?php if (p2_option( 'bio_bg', 0 ) == 'default' ) { ?>jQuery('#bio-inner').css('background', 'url(<?php echo get_bloginfo('template_directory'); ?>/images/bio-pageturn<?php if ( p2_option( 'biopicleftright', 0 ) == 'right' ) echo '-alt'; ?>.jpg) no-repeat top <?php if ( p2_option( 'biopicleftright', 0 ) == 'left') echo 'right'; else echo 'left'?>');
		<?php } ?>});
	});	
	<?php if ( p2_test( 'lazyloader', 'on' ) ) { ?>
	if (!jQuery.browser.msie) {	    
	    jQuery(".entry-content img").lazyload({
			effect : "fadeIn",
			threshold : 1500,
			placeholder : "<?php p2_imageurl( 'lazyloader' ); ?>" 
		});
	}<?php } ?>
		
	<?php if ( p2_test('no_right_click', ' ondragstart="return false" onselectstart="return false"') ) { ?> 
	jQuery('.alignnone, .aligncenter, .alignright, .alignleft, .gallery img, a[href$=.jpg], a[href$=.gif], a[href$=.png], a[href$=.JPG], a[href$=.GIF], a[href$=.PNG]')
		<?php if ( p2_test( 'no_left_click', 'on' ) ) { ?>.css('cursor', 'default')
		.click(function(){return false;})<?php } ?>
		.bind('contextmenu', function(){return false;}
	);
	<?php } ?>
	
	
	<?php if ( p2_test( 'custom_js_switch', 'on' ) && p2_test( 'custom_js_ready' ) ) p2_option( 'custom_js_ready' ); ?>
		 
});

// flash header area
<?php if ( p2_using_flash() ) { ?>var params = {
	FlashVars: "path2xml=<?php p2_static('xml'); p2_option('randomizer'); ?>",
	bgcolor: "<?php 
	if (p2_option( 'flashheader_bg_color_bind', 0 ) == 'on' ) {
		p2_option( 'flashheader_bg_color' ); 
	} else {
		p2_option( 'body_bg_color' );
	} ?>",
	wmode: "opaque"
}
swfobject.embedSWF("<?php bloginfo('template_url'); ?>/flash/flashheader.swf", "flash-header", "<?php echo $ff_width; ?>", "<?php echo $ff_height; ?>", "7.0.0", "<?php bloginfo('template_url'); ?>/flash/expressinstall.swf", false, params);<?php } ?>

<?php if ( p2_using_random_bio_images() ) { ?>
function randombiopics() {
	var biopics=new Array()
	
	<?php
	$c = 0;
	for ( $i = 1; $i <= 15; $i++ ) {
		if ( p2_image_exists( 'biopic' . $i ) ) {
			echo "biopics[$c]='<img id=\"biopic\" src=\"";
			p2_imageurl( 'biopic' . $i );
			echo '" ';
			p2_imageHTML( 'biopic1' );
			echo ' alt="';
			bloginfo('name');
			echo ' bio picture" />';
			echo "'\n\n\t";
			$c++;
		}
	} ?>
var biopic = Math.floor(Math.random()*(biopics.length));
	document.write(biopics[biopic]);
}	
<?php } ?>

<?php if ( !p2_test( 'audioplayer', 'off' ) ) {
	// create the treated mp3 paths
	$c = 1; $output = '';
	for ( $i = 1; $i <= 4; $i++ ) {
		$string = p2_imageurl( 'audio' . $i, 0 );
		// no uploaded file? check the URL override option
		if ( ( substr( $string, -1 ) == '/' ) || $string == '#' ) {
			$string = '';
			$string = p2_option( 'audioplayer_override_file' . $i, 0);			
			if ( $string ) $string = p2_url_add_http( $string );
		}
		if ( $string ) { // we have a file, prep it
			// if not the first, add the comma delimiter
			if ( $c > 1 ) $output = $output . '%2C';
			$c++;
			// replace the : and /
			$string = str_replace( '/', '%2F', $string );
			$string = str_replace( ':', '%3A', $string );
			$output = $output . $string;	
		}			
	}
	if ( !$output ) {
		$html = '<span style="background:#fff;color:red;">You must have at least one MP3 for the audio player to work.</span>';
	} else {
		// prepare the colors
		$options = array(
			'audioplayer_center_bg',
			'audioplayer_text'  ,
			'audioplayer_left_bg' ,
			'audioplayer_left_icon',
			'audioplayer_right_bg',
			'audioplayer_right_icon',
			'audioplayer_right_bg_hover',
			'audioplayer_right_icon_hover',
			'audioplayer_slider',
			'audioplayer_loader',
			'audioplayer_track',
			'audioplayer_track_border',
			);
		$all_colors = '';
		foreach ( $options as $option ) {
			$all_colors = $all_colors . p2_option( $option, 0 );
		}
		$all_colors = ltrim( $all_colors, '#' );
		$colors = explode( '#', $all_colors);

		// echo out the HTML
		$html = '<object type="application/x-shockwave-flash" data="';
		$html .= get_bloginfo( 'template_url', 'display' );
		$html .= '/flash/audioplayer.swf" width="290" height="24" id="audioplayer1"><param name="movie" value="';
		$html .= get_bloginfo( 'template_url', 'display' );	
		$html .= '/flash/audioplayer.swf"><param name="FlashVars" value="playerID=1&amp;bg=0x';
			$html .= $colors[0];
			$html .= '&amp;leftbg=0x';
			$html .= $colors[2];
			$html .= '&amp;lefticon=0x'; 
			$html .= $colors[3];
			$html .= '&amp;rightbg=0x';
			$html .= $colors[4];
			$html .= '&amp;rightbghover=0x'; 
			$html .= $colors[6];
			$html .= '&amp;righticon=0x'; 
			$html .= $colors[5];
			$html .= '&amp;righticonhover=0x';
			$html .= $colors[7]; 
			$html .= '&amp;text=0x';
			$html .= $colors[1];
			$html .= '&amp;slider=0x';
			$html .= $colors[8];
			$html .= '&amp;track=0x';
			$html .= $colors[10];
			$html .= '&amp;border=0x';
			$html .= $colors[11];
			$html .= '&amp;loader=0x';
			$html .= $colors[9];
			$html .= '&amp;autostart=';
			if ( p2_option( 'audioplayer_autostart', 0 ) == 'yes' ) $html .= 'yes';
			else $html .= 'no';
			$html .= '&amp;loop=';
			if ( p2_option( 'audioplayer_loop', 0 ) == 'yes' ) $html .= 'yes';
			else $html .= 'no';
			$html .= '&amp;soundFile=';
			$html .= $output; // these are the paths to the mp3s
			$html .='"><param name="quality" value="high"><param name="menu" value="false"><param name="bgcolor" value="#FFFFFF"></object>';
	} ?>
function audioplayer() {
	document.write('<?php echo $html; ?>');
}
<?php } ?>
<?php  // bio twitter embed
if ( ! p2_test( 'bio_twitter', 'off' ) ) {
	if ( p2_test( 'bio_twitter', 'display' ) ) {
		$badge = '<div id="twitter-badge" style="width:176px;text-align:center"><embed src="http://twitter.com/flash/twitter_badge.swf"  flashvars="color1=' . base_convert( p2_option( 'bio_twitter_color', 0 ), 16, 10 ) . '&type=user&id=' . p2_option( 'twitter_num_id', 0 ) . '"  quality="high" width="176" height="176" name="twitter_badge" align="middle" allowScriptAccess="always" wmode="transparent" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" /><br /><a style="font-size: 10px; color: '.p2_option( 'bio_twitter_color', 0 ).'; text-decoration: none" href="http://twitter.com/'.p2_option( 'twitter_name', 0 ).'">'.p2_option( 'twitter_linktext', 0 ).'</a></div>';	
	} else if ( p2_test( 'bio_twitter', 'interact' ) ) {
		$badge = '<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,124,0" width="290" height="350" id="TwitterWidget" align="middle"><param name="allowScriptAccess" value="always" /><param name="allowFullScreen" value="false" /><param name="movie" value="http://static.twitter.com/flash/widgets/profile/TwitterWidget.swf" /><param name="quality" value="high" /><param name="bgcolor" value="' . p2_option( 'body_bg_color', 0 ) . '" /><param name="FlashVars" value="userID=15383231&styleURL=http://static.twitter.com/flash/widgets/profile/' . p2_option( 'bio_twitter_style', 0 ) . '.xml"><embed src="http://static.twitter.com/flash/widgets/profile/TwitterWidget.swf" quality="high" bgcolor="' . p2_option( 'body_bg_color', 0 ) . '" width="290" height="350" name="TwitterWidget" align="middle" allowScriptAccess="sameDomain" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" FlashVars="userID=' . p2_option( 'twitter_num_id', 0 ) . '&styleURL=http://static.twitter.com/flash/widgets/profile/' . p2_option( 'bio_twitter_style', 0 ) . '.xml"/></object>';
	} ?>
function biotwitter() {
	document.write('<?php echo $badge; ?>')
}
<?php } ?>
<?php if ( p2_test( 'custom_js_switch', 'on' ) && p2_test( 'custom_js' ) ) p2_option( 'custom_js' ); ?>
