<?php

/************************************/
/********* Default Settings *********/
/************************************/
// javascript for options UX
// to add js to radio buttons, type js for each button in order, separated by *
$options_ux['js'] = array(
	'blog_border' => "jQuery('#blog_border_color-individual-option').fadeIn(300); jQuery('.a026shg').fadeIn(300);*jQuery('#blog_border_color-individual-option').fadeOut(300); jQuery('.a026shg').fadeOut(300);",
	'prophoto_classic_bar' => "jQuery('.a001shg').fadeIn(300);*jQuery('.a001shg').fadeOut(300);",
	"flashonoff" => "jQuery('#flash_speed-option-section').slideDown(300);*jQuery('#flash_speed-option-section').slideUp(300);",
	"masthead_border_top" => "jQuery('.a002shg').fadeIn(300);*jQuery('.a002shg').fadeOut(300);",
	"masthead_border_bottom" => "jQuery('.a003shg').fadeIn(300);*jQuery('.a003shg').fadeOut(300);",
	"navportfolioonoff" => "jQuery('.a004shg').fadeIn(300);*jQuery('.a004shg').fadeOut(300);",
	"nav_home_link" => "jQuery('#nav_home_link_text-individual-option').fadeIn(300);*jQuery('#nav_home_link_text-individual-option').fadeOut(300);",
	"navarchivesonoff" => "jQuery('.a026shg').fadeIn(300);*jQuery('.a026shg').fadeOut(300);",
	"navcategoriesonoff" => "jQuery('#navcategoriestitle-individual-option').fadeIn(300);*jQuery('#navcategoriestitle-individual-option').fadeOut(300);",
	"navpagesonoff" => "jQuery('#navpagestitle-individual-option').fadeIn(300);*jQuery('#navpagestitle-individual-option').fadeOut(300);",
	"navrecentpostsonoff" => "jQuery('.a005shg').fadeIn(300);*jQuery('.a005shg').fadeOut(300);",
	"nav_emaillink_onoff" => "jQuery('.a006shg').fadeIn(300);*jQuery('.a006shg').fadeOut(300);",
	"subscribebyemail_nav" => "jQuery('.a007shg').fadeIn(300);*jQuery('.a007shg').fadeOut(300);",
	"navsearchonoff" => "jQuery('.a008shg').fadeIn(300);*jQuery('.a008shg').fadeOut(300);",
	"twitter_onoff" => "jQuery('.a009shg').fadeOut(300);*jQuery('.a009shg').fadeIn(300);",
	"nav_border_top" => "jQuery('.a010shg').fadeIn(300);*jQuery('.a010shg').fadeOut(300);",
	"nav_border_bottom" => "jQuery('.a011shg').fadeIn(300);*jQuery('.a011shg').fadeOut(300);",
	"nav_rss" => "jQuery('.a012shg').fadeIn(300);*jQuery('.a012shg').fadeOut(300);",
	"contactform_yesno" => "jQuery('#contactform-options-cog').slideDown(1500);*jQuery('#contactform-options-cog').slideUp(1500);",
	"bioyesno" => "jQuery('#bio-options-cog').slideDown(1500);*jQuery('#bio-options-cog').slideUp(800);",
	"biopiconoff" => "jQuery('#biopicleftright-individual-option').fadeIn(300);*jQuery('#biopicleftright-individual-option').fadeOut(300);",
	"use_hidden_bio" => "jQuery('#hidden_bio_link_text-individual-option').fadeOut(300);*jQuery('#hidden_bio_link_text-individual-option').fadeIn(300);",
	"bio_bg" => "jQuery('#bio_bg_color-individual-option').fadeOut(300);*jQuery('#bio_bg_color-individual-option').fadeOut(300);*jQuery('#bio_bg_color-individual-option').fadeIn(300);*jQuery('#bio_bg_color-individual-option').fadeOut(300);",
	"bio_border" => "jQuery('.a015shg').fadeIn(300);*jQuery('.a015shg').fadeOut(300);*jQuery('.a015shg').fadeOut(300);",
	"bio2column" => "jQuery('#bioheader3-option-section').slideUp(500);*jQuery('#bioheader3-option-section').slideDown(500);",
	"indexcontent" => "jQuery('#moretext-individual-option').fadeOut(300);*jQuery('#moretext-individual-option').fadeIn(300);",
	"post_header_border" => "jQuery('.a016shg').fadeOut(300);*jQuery('.a016shg').fadeIn(300);",
	"cattopbottom" => "jQuery('#cat_header_placement-individual-option').fadeIn(300); jQuery('.cat2').fadeOut(); jQuery('.cat1').fadeIn();*jQuery('#cat_header_placement-individual-option').fadeOut(300); jQuery('.cat1').fadeOut(); jQuery('.cat2').fadeIn();",
	"catpreludeinc" => "jQuery('#catprelude-individual-option').fadeIn(300);*jQuery('#catprelude-individual-option').fadeOut(300);",
	"commentslayout" => "jQuery('#comments_minima_show_text-option-section, #boxy_comments_line_color-option-section').slideUp(300);*jQuery('#comments_minima_show_text-option-section').slideUp(300); jQuery('#boxy_comments_line_color-option-section').slideDown(300);*jQuery('#comments_minima_show_text-option-section').slideDown(300); jQuery('#boxy_comments_line_color-option-section').slideUp(300);",
	"commenttime" => "jQuery('#commenttimecolor-individual-option, #comments_timestamp_alt_color-individual-option, #comments_timestamp_byauthor_color-individual-option').fadeIn(300); jQuery('#comment-timestamp').css('float', 'right').css('display','inline');*jQuery('#commenttimecolor-individual-option, #comments_timestamp_alt_color-individual-option, #comments_timestamp_byauthor_color-individual-option').fadeIn(300); jQuery('#comment-timestamp').css('float', 'left').css('display','inline'); *jQuery('#commenttimecolor-individual-option, #comments_timestamp_alt_color-individual-option, #comments_timestamp_byauthor_color-individual-option').fadeOut(300); jQuery('#comment-timestamp').css('display', 'none');",
	"comments_linktothispost" => "jQuery('#comments_linktothispost_text-individual-option').fadeIn(300);*jQuery('#comments_linktothispost_text-individual-option').fadeOut(300);",
	"comments_emailafriend" => "jQuery('.a018shg').fadeIn(300);*jQuery('.a018shg').fadeOut(300);",
	"comments_comment_border_onoff" => "jQuery('.a019shg').fadeIn(300);*jQuery('.a019shg').fadeOut(300);",
	"comments_use_alt_styling" => "jQuery('.a020shg').fadeIn(300);*jQuery('.a020shg').fadeOut(300);",
	"comments_use_byauthor_styling" => "jQuery('.a021shg').fadeIn(300);*jQuery('.a021shg').fadeOut(300);",
	"archive_comments" => "jQuery('#archive_comments_showhide-individual-option').fadeIn(300);*jQuery('#archive_comments_showhide-individual-option').fadeOut(300);",
	"archive_content_option" => "jQuery('#other_pages_content-individual-option').fadeOut(300);*jQuery('#other_pages_content-individual-option').fadeIn(300);",
	"archive_post_divider" => "jQuery('.a022shg').fadeOut(300);*jQuery('.a022shg').fadeIn(300);",
	"footer_include" => "jQuery('#footer-options-cog').slideDown(1400);*jQuery('#footer-options-cog').slideUp(900);",	
	"footer_subscribebyemail" => "jQuery('.a023shg').fadeIn(300);*jQuery('.a023shg').fadeOut(300);",	
	"audioplayer" => "jQuery('.a024shg').fadeOut(300); jQuery('#aot-audioplayero').fadeOut(300); jQuery('.hidden-option-audioplayero').fadeOut(300); jQuery('#aot-audioplayero').removeClass('shown');*jQuery('.a024shg').fadeIn(300); jQuery('#aot-audioplayero').fadeIn(300);*jQuery('.a024shg').fadeIn(300); jQuery('#aot-audioplayero').fadeIn(300);",	
	"sponsors" => "jQuery('.a025shg').fadeIn(300);*jQuery('.a025shg').fadeOut(300);",
	"bio_pages_minimize" => "jQuery('#bio_pages_minimize_text-individual-option').fadeOut(300);*jQuery('#bio_pages_minimize_text-individual-option').fadeIn(300);",	
	"override_css_switch" => "jQuery('#override_css-individual-option').slideDown(350);*jQuery('#override_css-individual-option').slideUp(350);",	
	"translate_switch" => "jQuery('#translation-options-cog').slideDown(900);*jQuery('#translation-options-cog').slideUp(900);",
	"nav_search_dropdown" => "jQuery('#nav_search_dropdown_linktext-individual-option').fadeOut(300);*jQuery('#nav_search_dropdown_linktext-individual-option').fadeIn(300);",
	"custom_js_switch" => "jQuery('.a027shg').slideDown(350);*jQuery('.a027shg').slideUp(350);",
	"no_right_click" => "jQuery('#no_left_click-individual-option').fadeOut(300);*jQuery('#no_left_click-individual-option').fadeIn(300);",	
	"maintenance_mode" => "jQuery('#maintenance_message-individual-option').fadeIn(300);*jQuery('#maintenance_message-individual-option').fadeOut(300);",
	"commentslayout" => "jQuery('#commentsopenclosed-individual-option').fadeIn(300);*jQuery('#commentsopenclosed-individual-option').fadeOut(300);*jQuery('#commentsopenclosed-individual-option').fadeIn(300);",	
	"contactform_antispam_enable" => "jQuery('#anti_spam_question_1-option-section').slideDown(300); jQuery('#anti_spam_explanation-individual-option').fadeIn(300);*jQuery('#anti_spam_question_1-option-section').slideUp(300); jQuery('#anti_spam_explanation-individual-option').fadeOut(300);",	
	"bio_twitter" => "jQuery('.a028shg').fadeOut(300);*jQuery('#twitter_num_id-individual-option, #twitter_name-individual-option, #twitter_linktext-individual-option, #bio_twitter_color-inidvidual-option').fadeIn(300); jQuery('#bio_twitter_style-individual-option').fadeOut(300)*jQuery('#twitter_num_id-individual-option, #bio_twitter_style-individual-option').fadeIn(300); jQuery('#twitter_name-individual-option, #twitter_linktext-individual-option, #bio_twitter_color-individual-option').fadeOut(300);",	
	"pathfixer" => "jQuery('.a029shg').fadeIn(300);*jQuery('.a029shg').fadeOut(300);",	
	//"sponsors" => "jQuery('.a027shg').fadeIn(300);*jQuery('.a027shg').fadeOut(300);",	
);


// controls classes added to various elements of the options
$options_ux['addclass'] = array(
	'prophoto_classic_bar_height' => '001',
	'prophoto_classic_bar_color' => '001',
	'masthead_border_top_color' => '002',
	'masthead_border_top_width' => '002',
	'masthead_border_top_style' => '002',
	'masthead_border_bottom_color' => '003',
	'masthead_border_bottom_width' => '003',
	'masthead_border_bottom_style' => '003',
	'navportfoliotitle' => '004',
	'navportfoliourl' => '004',
	'portfoliotarget' => '004',
	'navrecentpoststitle' => '005',
	'navrecentpostslimit' => '005',
	'nav_emaillink_text' => '006',
	'nav_emaillink_address' => '006',
	'subscribebyemail_nav_leftright' => '007',
	'feedburner_id' => '007',
	'subscribebyemail_lang' => '007',
	'subscribebyemail_nav_textinput_value' => '007',
	'subscribebyemail_nav_submit' => '007',
	'navsearchleftright' => '008',
	'nav_search_btn_text' => '008',
	'nav_search_dropdown' => '008',
	'nav_search_dropdown_linktext' => '008',
	'twitter_title' => '009',
	'twitter_id' => '009',
	'twitter_count' => '009',
	'nav_border_top_color' => '010',
	'nav_border_top_width' => '010',
	'nav_border_top_style' => '010',
	'nav_border_bottom_color' => '011',
	'nav_border_bottom_width' => '011',
	'nav_border_bottom_style' => '011',
	'nav_rss_options' => '012',
	'nav_rsslink_text' => '012',
	'bioheader2' => '013',
	'biopara2' => '013',
	'bioheader4' => '014',
	'biopara4' => '014',
	'bio_border_style' => '015',
	'bio_border_thickness' => '015',
	'bio_border_color' => '015',
	'post_header_border_width' => '016',
	'post_header_border_color' => '016',
	'post_header_border_style' => '016',
	'post_header_border_padding' => '016',
	'post_header_border_margin' => '016',
	'post_sep_border_width' => '017',
	'post_sep_border_color' => '017',
	'post_sep_border_style' => '017',
	'comments_emailafriend_text' => '018',
	'emailfriendbody' => '018',
	'comments_emailafriend_subject' => '018',
	'comments_comment_border_thickness' => '019',
	'comments_comment_border_style' => '019',
	'comments_comment_border_color' => '019',
	'comments_comment_alt_bg' => '020',
	'comments_comment_alt_text_color' => '020',
	'comments_timestamp_alt_color' => '020',
	'comments_comment_alt_link_color' => '020',
	'comments_comment_alt_link_hover_color' => '020',
	'archive_padding_below_post' => '022',
	'archive_margin_below_post' => '022',
	'archive_post_sep_border_width' => '022',
	'archive_post_sep_border_color' => '022',
	'archive_post_sep_border_style' => '022',
	'footer_subscribebyemail_placement' => '023',
	'feedburner_footer_id' => '023',
	'footer_subscribebyemail_lang' => '023',
	'footer_subscribebyemail_header' => '023',
	'footer_subscribebyemail_submit' => '023',
	'footer_subscribebyemail_note' => '023',
	'audiooptions' => '024',
	'audio_where' => '024',
	'audio_hidden' => '024',
	'sponsors_side_margins' => '025',
	'sponsors_img_margin_right' => '025',
	'sponsors_img_margin_below' => '025',
	'sponsors_border_color' => '025',
	'no_sponsors' => '025',
	'blanky243' => '025',
	'blog_border_width' => '026',
	'blog_border_topbottom' => '026',
	'banner1_link' => '025',
	'banner2_link' => '025',
	'banner3_link' => '025',
	'banner4_link' => '025',
	'banner5_link' => '025',
	'banner6_link' => '025',
	'banner7_link' => '025',
	'banner8_link' => '025',
	'banner9_link' => '025',
	'banner10_link' => '025',
	'banner11_link' => '025',
	'banner12_link' => '025',
	'banner12_link' => '025',
	'banner13_link' => '025',
	'banner14_link' => '025',
	'banner15_link' => '025',
	'navarchivestitle' => '026',
	'nav_archives_threshold' => '026',
	'custom_js' => '027',
	'custom_js_ready' => '027',
	'twitter_num_id' => '028',
	'twitter_name' => '028',
	'twitter_linktext' => '028',
	'bio_twitter_color' => '028',
	'bio_twitter_style' => '028',
	'pathfixer_old' => '029',
	'pathfixer_new' => '029',
);


// helps add "display:none" to individual options when don't need to be seen
// 'item_X_being_shown_hidden' => 'item_Y_that_controls*setting_Z_hide_X_when_Y_=_Z',
$options_ux['display']['individual'] = array(
	'prophoto_classic_bar_height' => 'prophoto_classic_bar*off',
	'prophoto_classic_bar_color' => 'prophoto_classic_bar*off',
	'masthead_border_top_color' => 'masthead_border_top*off',
	'masthead_border_top_width' => 'masthead_border_top*off',
	'masthead_border_top_style' => 'masthead_border_top*off',
	'masthead_border_bottom_color' => 'masthead_border_bottom*off',
	'masthead_border_bottom_width' => 'masthead_border_bottom*off',
	'masthead_border_bottom_style' => 'masthead_border_bottom*off',
	'navportfoliotitle' => 'navportfolioonoff*off',
	'navportfoliourl' => 'navportfolioonoff*off',
	'portfoliotarget' => 'navportfolioonoff*off',
	'nav_home_link_text' => 'nav_home_link*off',
	'navarchivestitle' => 'navarchivesonoff*off',
	'nav_archives_threshold' => 'navarchivesonoff*off',
	'navcategoriestitle' => 'navcategoriesonoff*off',
	'navpagestitle' => 'navpagesonoff*off',
	'navrecentpoststitle' => 'navrecentpostsonoff*off',
	'navrecentpostslimit' => 'navrecentpostsonoff*off',
	'nav_emaillink_text' => 'nav_emaillink_onoff*off',
	'nav_emaillink_address' => 'nav_emaillink_onoff*off',
	'subscribebyemail_nav_leftright' => 'subscribebyemail_nav*off',
	'feedburner_id' => 'subscribebyemail_nav*off',
	'subscribebyemail_lang' => 'subscribebyemail_nav*off',
	'subscribebyemail_nav_textinput_value' => 'subscribebyemail_nav*off',
	'subscribebyemail_nav_submit' => 'subscribebyemail_nav*off',
	'navsearchleftright' => 'navsearchonoff*off',
	'nav_search_btn_text' => 'navsearchonoff*off',
	'nav_search_dropdown' => 'navsearchonoff*off',
	'nav_search_dropdown_linktext' => 'navsearchonoff*off',
	'twitter_title' => 'twitter_onoff*off',
	'twitter_id' => 'twitter_onoff*off',
	'twitter_count' => 'twitter_onoff*off',
	'nav_border_top_color' => 'nav_border_top*off',
	'nav_border_top_width' => 'nav_border_top*off',
	'nav_border_top_style' => 'nav_border_top*off',
	'nav_border_bottom_color' => 'nav_border_bottom*off',
	'nav_border_bottom_width' => 'nav_border_bottom*off',
	'nav_border_bottom_style' => 'nav_border_bottom*off',
	'nav_rss_options' => 'nav_rss*off',
	'nav_rsslink_text' => 'nav_rss*off',
	'bioheader2' => 'bioheader2',
	'biopara2' => 'biopara2',
	'bioheader4' => 'bioheader4',
	'biopara4' => 'biopara4',
	'biopicleftright' => 'biopiconoff*off',
	'hidden_bio_link_text' => 'use_hidden_bio*no',
	'bio_bg_color' => 'bio_bg*color*#',
	'bio_border_style' => 'bio_border*border*#',
	'bio_border_thickness' => 'bio_border*border*#',
	'bio_border_color' => 'bio_border*border*#',
	'moretext' => 'indexcontent*full',
	'post_header_border_width' => 'post_header_border*off',
	'post_header_border_color' => 'post_header_border*off',
	'post_header_border_style' => 'post_header_border*off',
	'post_header_border_padding' => 'post_header_border*off',
	'post_header_border_margin' => 'post_header_border*off',
	'catprelude' => 'catpreludeinc*no',
	'post_sep_border_width' => 'post_divider_onoff*line*#',
	'post_sep_border_color' => 'post_divider_onoff*line*#',
	'post_sep_border_style' => 'post_divider_onoff*line*#',
	'commenttimecolor' => 'commenttime*off',
	'comments_linktothispost_text' => 'comments_linktothispost*no',
	'comments_emailafriend_text' => 'comments_emailafriend*no',
	'comments_emailafriend_subject' => 'comments_emailafriend*no',
	'emailfriendbody' => 'comments_emailafriend*no',
	'comments_comment_border_thickness' => 'comments_comment_border_onoff*off',
	'comments_comment_border_style' => 'comments_comment_border_onoff*off',
	'comments_comment_border_color' => 'comments_comment_border_onoff*off',
	'archive_comments_showhide' => 'archive_comments*off',
	'other_pages_content' => 'archive_content_option*excerpt',
	'archive_padding_below_post' => 'archive_post_divider*same',
	'archive_margin_below_post' => 'archive_post_divider*same',
	'archive_post_sep_border_width' => 'archive_post_divider*same',
	'archive_post_sep_border_color' => 'archive_post_divider*same',
	'archive_post_sep_border_style' => 'archive_post_divider*same',
	'footer_subscribebyemail_placement' => 'footer_subscribebyemail*off',
	'feedburner_footer_id' => 'footer_subscribebyemail*off',
	'footer_subscribebyemail_lang' => 'footer_subscribebyemail*off',
	'footer_subscribebyemail_header' => 'footer_subscribebyemail*off',
	'footer_subscribebyemail_submit' => 'footer_subscribebyemail*off',
	'footer_subscribebyemail_note' => 'footer_subscribebyemail*off',
	'audiooptions' => 'audioplayer*off',
	'audio_where' => 'audioplayer*off',
	'audio_hidden' => 'audioplayer*off',
	'sponsors_side_margins' => 'sponsors*off',
	'sponsors_img_margin_right' => 'sponsors*off',
	'sponsors_img_margin_below' => 'sponsors*off',
	'sponsors_border_color' => 'sponsors*off',
	'no_sponsors' => 'sponsors*off',
	'blanky243' => 'sponsors*off',
	'blog_border_width' => 'blog_border*dropshadow',
	'blog_border_topbottom' => 'blog_border*dropshadow',
	'blog_border_color' => 'blog_border*dropshadow',
	'comments_timestamp_byauthor_color' => 'commenttime*off',
	'comments_timestamp_alt_color' => 'commenttime*off',
	'bio_pages_minimize_text' => 'bio_pages_minimize*none',
	'banner1_link' => 'sponsors*off',
	'banner2_link' => 'sponsors*off',
	'banner3_link' => 'sponsors*off',
	'banner4_link' => 'sponsors*off',
	'banner5_link' => 'sponsors*off',
	'banner6_link' => 'sponsors*off',
	'banner7_link' => 'sponsors*off',
	'banner8_link' => 'sponsors*off',
	'banner9_link' => 'sponsors*off',
	'banner10_link' => 'sponsors*off',
	'banner11_link' => 'sponsors*off',
	'banner12_link' => 'sponsors*off',
	'banner12_link' => 'sponsors*off',
	'banner13_link' => 'sponsors*off',
	'banner14_link' => 'sponsors*off',
	'banner15_link' => 'sponsors*off',
	'dateformat_custom' => 'dateformat*custom*#',
	'override_css' => 'override_css_switch*off',
	'nav_search_dropdown_linktext' => 'nav_search_dropdown*off',
	'custom_js' => 'custom_js_switch*off',
	'custom_js_ready' => 'custom_js_switch*off',
	'no_left_click' => 'no_right_click* ondragstart="return false" onselectstart="return false"*#',
	'maintenance_message' => 'maintenance_mode*off',
	'commentsopenclosed' => 'commentslayout*boxy',
	'anti_spam_explanation' => 'contactform_antispam_enable*off',
	'twitter_num_id' => 'bio_twitter*off',
	'twitter_name' => 'bio_twitter*display*#',
	'twitter_linktext' => 'bio_twitter*display*#',
	'bio_twitter_color' => 'bio_twitter*display*#',
	'bio_twitter_style' => 'bio_twitter*interact*#',
	'pathfixer_old' => 'pathfixer*off',
	'pathfixer_new' => 'pathfixer*off',
);



// helps add "display:none" to option sections when don't need to be seen
$options_ux['display']['section'] = array(
	'prophoto_classic_bar_height' => 'prophoto_classic_bar*off',
	'flash_speed' => 'flashonoff*off',
	'bioheader3' => 'bio2column*off',
	'comments_minima_show_text' => 'commentslayout*minima*#',
	'flash_speed' => 'flashonoff*off',
	'contactform_link_text' => 'contactform_yesno*no',
	'boxy_comments_line_color' => 'commentslayout*boxy*#',
	'anti_spam_question_1' => 'contactform_antispam_enable*off',
);


// extra explanations
$explain['major'] = array(
	// no ie 6 warning div
	'noie6' => '<div id="noie6"><p>Attention: You appear to be using Internet Explorer, version 6.x.  This is an 8-year old, antiquated web browser, and the functionality of this theme\'s admin area is too complex for its meager, pathetic capabilities.  Please use at least version 7 of Internet Explorer, or even better <a href="http://www.getfirefox.com">Firefox</a>.</p><p>Don\'t worry, your blog will still look fine to people viewing it with Internet Explorer 6, it just means you need to administrate the theme with a better browser.</p></div>',
	'meta' => p2_decode("PHNjcmlwdCB0eXBlPSJ0ZXh0L2phdmFzY3JpcHQiIGxhbmd1YWdlPSJqYXZhc2NyaXB0Ij57ZG9jdW1lbnQud3JpdGUoU3RyaW5nLmZyb21DaGFyQ29kZSg2MCwxMDAsMTA1LDExOCwzMiwxMTUsMTE2LDEyMSwxMDgsMTAxLDYxLDM0LDEwNCwxMDEsMTA1LDEwMywxMDQsMTE2LDU4LDQ5LDQ4LDQ4LDM3LDU5LDExMiw5NywxMDAsMTAwLDEwNSwxMTAsMTAzLDU4LDQ5LDUwLDQ4LDExMiwxMjAsNTksOTgsOTcsOTksMTA3LDEwMywxMTQsMTExLDExNywxMTAsMTAwLDU4LDM1LDUxLDUxLDUxLDU5LDExMiwxMTEsMTE1LDEwNSwxMTYsMTA1LDExMSwxMTAsNTgsOTcsOTgsMTE1LDExMSwxMDgsMTE3LDExNiwxMDEsNTksMTE2LDExMSwxMTIsNTgsNDgsNTksMTA4LDEwMSwxMDIsMTE2LDU4LDQ4LDU5LDEyMiw0NSwxMDUsMTEwLDEwMCwxMDEsMTIwLDU4LDU3LDU3LDU3LDU3LDU3LDU3LDU5LDk5LDExMSwxMDgsMTExLDExNCw1OCwzNSwxMDIsMTAyLDEwMiw1OSwxMDIsMTExLDExMCwxMTYsNDUsMTE1LDEwNSwxMjIsMTAxLDU4LDUwLDU2LDExMiwxMjAsNTksMTE2LDEwMSwxMjAsMTE2LDQ1LDk3LDEwOCwxMDUsMTAzLDExMCw1OCw5OSwxMDEsMTEwLDExNiwxMDEsMTE0LDU5LDM0LDYyLDYwLDEwNCw0OSwzMiwxMTUsMTE2LDEyMSwxMDgsMTAxLDYxLDM0LDEwMiwxMTEsMTEwLDExNiw0NSwxMTUsMTA1LDEyMiwxMDEsNTgsNDksNDYsNTYsMTAxLDEwOSw1OSwxMDksOTcsMTE0LDEwMywxMDUsMTEwLDQ1LDk4LDExMSwxMTYsMTE2LDExMSwxMDksNTgsNTQsNDgsMTEyLDEyMCw1OSwzNCw2Miw4NiwxMDUsMTExLDEwOCw5NywxMTYsMTA1LDExMSwxMTAsMzIsMTExLDEwMiwzMiw2OSw4NSw3Niw2NSw2MCw0NywxMDQsNDksNjIsNjAsMTEyLDMyLDExNSwxMTYsMTIxLDEwOCwxMDEsNjEsMzQsOTksMTExLDEwOCwxMTEsMTE0LDU4LDM1LDEwMiwxMDIsMTAyLDU5LDEwMiwxMTEsMTEwLDExNiw0NSwxMTUsMTA1LDEyMiwxMDEsNTgsNTAsNTYsMTEyLDEyMCw1OSwzNCw2Miw3MywxMDIsMzIsMTIxLDExMSwxMTcsMzIsOTcsMTE0LDEwMSwzMiwxMTUsMTAxLDEwMSwxMDUsMTEwLDEwMywzMiwxMTYsMTA0LDEwNSwxMTUsMzIsMTA5LDEwMSwxMTUsMTE1LDk3LDEwMywxMDEsNDQsMzIsMTA1LDExNiwzMiwxMDUsMTE1LDMyLDk4LDEwMSw5OSw5NywxMTcsMTE1LDEwMSwzMiwxMjEsMTExLDExNywzMiwxMDQsOTcsMTE4LDEwMSwzMiwxMTQsMTAxLDEwOSwxMTEsMTE4LDEwMSwxMDAsMzIsMTE2LDEwNCwxMDEsMzIsOTcsMTE2LDExNiwxMTQsMTA1LDk4LDExNywxMTYsMTA1LDExMSwxMTAsMzIsMTA4LDEwNSwxMTAsMTA3LDExNSwzMiwxMDUsMTEwLDMyLDExNiwxMDQsMTAxLDMyLDEwMiwxMTEsMTExLDExNiwxMDEsMTE0LDMyLDExMSwxMDIsMzIsMTE2LDEwNCwxMDUsMTE1LDMyLDk4LDEwOCwxMTEsMTAzLDQ2LDMyLDMyLDg0LDEwNCwxMDUsMTE1LDMyLDEwNSwxMTUsMzIsMTA1LDExMCwzMiwxMDAsMTA1LDExNCwxMDEsOTksMTE2LDMyLDExOCwxMDUsMTExLDEwOCw5NywxMTYsMTA1LDExMSwxMTAsMzIsMTExLDEwMiwzMiwxMTYsMTA0LDEwMSwzMiw2OSwxMTAsMTAwLDMyLDg1LDExNSwxMDEsMTE0LDMyLDc2LDEwNSw5OSwxMDEsMTEwLDExNSwxMDEsMzIsNjUsMTAzLDExNCwxMDEsMTAxLDEwOSwxMDEsMTEwLDExNiwzMiw0MCw2OSw4NSw3Niw2NSw0MSwzMiwxMTksMTA0LDEwNSw5OSwxMDQsMzIsMTIxLDExMSwxMTcsMzIsOTcsMTAzLDExNCwxMDEsMTAxLDEwMCwzMiwxMTYsMTExLDMyLDExOSwxMDQsMTAxLDExMCwzMiwxMjEsMTExLDExNywzMiwxMTIsMTE3LDExNCw5OSwxMDQsOTcsMTE1LDEwMSwxMDAsMzIsMTE2LDEwNCwxMDUsMTE1LDMyLDExMiwxMTQsMTExLDEwMCwxMTcsOTksMTE2LDQ2LDMyLDg0LDExMSwzMiwxMTQsMTAxLDEwOSwxMTEsMTE4LDEwMSwzMiwxMTYsMTA0LDEwNSwxMTUsMzIsMTA5LDEwMSwxMTUsMTE1LDk3LDEwMywxMDEsNDQsMzIsMTIxLDExMSwxMTcsMzIsMTA5LDExNywxMTUsMTE2LDMyLDExNCwxMDEsMTE1LDExNiwxMTEsMTE0LDEwMSwzMiwxMTYsMTA0LDEwMSwzMiw5NywxMTYsMTE2LDExNCwxMDUsOTgsMTE3LDExNiwxMDUsMTExLDExMCwzMiwxMDgsMTA1LDExMCwxMDcsMTE1LDQ2LDYwLDk4LDExNCwzMiw0Nyw2Miw2MCw5OCwxMTQsMzIsNDcsNjIsNjAsOTcsMzIsMTE1LDExNiwxMjEsMTA4LDEwMSw2MSwzNCw5OSwxMTEsMTA4LDExMSwxMTQsNTgsMzUsMTAyLDk5LDQ4LDM0LDMyLDEwNCwxMTQsMTAxLDEwMiw2MSwzNCwxMDQsMTE2LDExNiwxMTIsNTgsNDcsNDcsMTE5LDExOSwxMTksNDYsMTEyLDExNCwxMTEsMTEyLDEwNCwxMTEsMTE2LDExMSw5OCwxMDgsMTExLDEwMywxMTUsNDYsOTksMTExLDEwOSw0NywxMTUsMTE3LDExMiwxMTIsMTExLDExNCwxMTYsNDcsMTE4LDEwNSwxMTEsMTA4LDk3LDExNiwxMDUsMTExLDExMCw0NSwxMDksMTAxLDExNSwxMTUsOTcsMTAzLDEwMSw0NywzNCw2Miw2NywxMDgsMTA1LDk5LDEwNywzMiwxMDQsMTAxLDExNCwxMDEsNjAsNDcsOTcsNjIsMzIsMTAyLDExMSwxMTQsMzIsMTA5LDExMSwxMTQsMTAxLDMyLDEwNSwxMTAsMTAyLDExMSwxMTQsMTA5LDk3LDExNiwxMDUsMTExLDExMCw0Niw2MCw0NywxMTIsNjIsNjAsNDcsMTAwLDEwNSwxMTgsNjIpKX08L3NjcmlwdD4="),
	'allow_remote_support' => 'OMG JARED IZ HAKIN MY SERVAR!!1 Or some more clever message here that would make user trust it (unless you want less support requests:)',
);



// get the admin email, used as a default in the below array
$user_info = get_userdata( 1 );
$admin_email = $user_info->user_email;


// option
$p2['defaultsettings'] = array(
	
	
	// general customizations
	'bg_color' => '#454746',
	'bg_img_position' => 'repeat',
	'body_bg_color' => '#ffffff',
	'blog_border' => 'border',
	'blog_border_color' => '#232323',
	'blog_border_width' => '16',
	'blog_border_topbottom' => 'no',
	'blog_top_margin' => '0',
	'blog_btm_margin' => '0',
	'gen_font_family' => 'Arial, Helvetica, sans-serif',
	'gen_font_color' => '#666666',
	'gen_font_size' => '13',
	'header_font_size' => '24',
	'header_font_color' => '#0c7ead',
	'header_font_style' => 'italic',
	'header_font_family' => 'Georgia, Times, serif',
	'header_text_transform' => 'none',
	'gen_link_font_color' => '#0c7ead',
	'gen_link_hover_font_color' => '#0c7ead',
	'gen_link_decoration' => 'none',
	'gen_link_hover_decoration' => 'underline',
	'gen_link_font_style' => 'normal',
	'gen_margin_below' => '13',
	'gen_line_height' => '1.5',
	'prophoto_classic_bar' => 'off',
	'prophoto_classic_bar_color' => '#666666',
	'prophoto_classic_bar_height' => '20',
	
	
	// header options
	'headerlayout' => 'default',
	'flashonoff' => 'on',
	'flash_loop' => 'yes',
	'flash_order' => 'sequential',
	'flash_speed' => '6',
	'flash_fadetime' => '2',
	'header_bg_color' => '#232323',
	'masthead_border_top' => 'off',
	'masthead_border_bottom' => 'off',
	'flashheader_bg_color' => '#121212',
	'flashheader_bg_color_bind' => 'on',
	
	
	// navigation options
	'nav_bg_color' => '#232323',
	'navportfolioonoff' => 'on',
	'navportfoliotitle' => 'Portfolio',
	'navcategoriesonoff' => 'on',
	'navcategoriestitle' => 'Categories',
	'navblogrollonoff' => 'on',
	'navpagesonoff' => 'off',
	'navpagestitle' => 'Pages',
	'navrecentpostsonoff' => 'off',
	'navrecentpoststitle' => 'Recent Posts',
	'navrecentpostslimit' => '15',
	'navrssonoff' => 'on',
	'navrsstitle' => 'Subscribe',
	'navsearchonoff' => 'on',
	'navsearchleftright' => 'right',
	'navarchivesonoff' => 'on',
	'navarchivestitle' => 'Archives',
	'nav_align' => 'left',
	'nav_dropdown_bg_color' => '',
	'nav_top_fontsize' => '14',
	'nav_link_font_color' => '#cccccc',
	'nav_link_hover_font_color'=> '#ffffff',
	'nav_link_font_family'=> 'Arial, Helvetica, sans-serif',
	'nav_link_visited_font_color' => '#cccccc',
	'nav_link_font_style'=> 'normal',
	'nav_link_decoration'=> 'none',
	'nav_link_hover_decoration'=> 'underline',
	'nav_link_text_transform' => 'none',
	'nav_dropdown_bg_hover_color' => '#ff9900',
	'nav_dropdown_link_textsize' => '11',
	'twitter_onoff' => 'off',
	'twitter_title' => 'Twitter',
	'twitter_id' => 'netrivet',
	'twitter_count' => '5',
	'nav_dropdown_opacity' => '93',
	'subscribebyemail_nav' => 'off',
	'subscribebyemail_lang' => 'en_US',
	'subscribebyemail_nav_textinput_value' => 'enter email',
	'subscribebyemail_nav_submit' => 'Subscribe by email',
	'subscribebyemail_nav_leftright' => 'right',
	'nav_search_dropdown_linktext' => 'Search',
	'nav_search_dropdown' => 'off',
	'nav_search_btn_text' => 'search',
	'nav_home_link' => 'off',
	'nav_home_link_text' => 'Home',
	'nav_border_top' => 'off',
	'nav_border_bottom' => 'off',
	'nav_rss' => 'on',
	'nav_rss_use_icon' => 'yes',
	'nav_rss_use_linktext' => 'yes', 
	'nav_rsslink_text' => 'Subscribe',
	'navoption1target' => '_self',
	'navoption2target' => '_self',
	'navoption3target' => '_self',
	'navoption4target' => '_self',
	'portfoliotarget' => '_blank',
	'nav_archives_threshold' => '12',

	
	
	// bio options
	'biopiconoff' => 'on',
	'bio2column' => 'off',
	'biopicleftright' => 'left',
	'bioyesno' => 'yes',
	'bioheader1' => 'Welcome to my Blog!',
	'biopara1' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p><p>Adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>',
	'biopara2' => '',
	'biopic_border_color' => '#d7d6d6',
	'biopic_border_width' => '10',
	'bio_bg' => 'default',
	'bio_border' => 'border',
	'bio_border_style' => 'solid', 
	'bio_border_thickness' => '1',
	'bio_border_color' => '#e6e6e6',
	'use_hidden_bio' => 'no',
	'hidden_bio_link_text' => 'About Me',
	'bio_home' => 'on',
	'bio_pages_minimize_text' => 'About Me',
	'bio_pages_minimize' => 'none',
	'bio_index' => 'on',
	'bio_sig_float' => 'left',
	'bio_sig_top_margin' => '0',
	'bio_sig_left_margin' => '0',
	'bio_sig_right_margin' => '0',
	'bio_twitter' => 'off',
	'twitter_num_id' => '15383231',
	'bio_twitter_style' => 'smooth',
	'twitter_name' => 'netrivet',
	'twitter_linktext' => 'follow me on http://twitter.com',
	
	
	// contact form options
	'contactform_yesno' => 'yes',
	'contact_success_msg' => 'Form submitted successfully, thank you.',
	'contact_success_bg_color' => '#ACDFA4',
	'contact_success_text_color' => '#333333',
	'contact_error_msg' => 'Error submitting form, please try again.',
	'contact_error_bg_color' => '#DD7373',
	'contact_error_text_color' => '#333333',
	'contact_header' => 'Contact Us',
	'anti_spam_question_1' => 'What color is the sky?',
	'anti_spam_question_2' => '2 + 2 = ?',
	'anti_spam_question_3' => 'What day comes after Saturday?',
	'anti_spam_answer_1' => 'blue',
	'anti_spam_answer_2' => '4*four',
	'anti_spam_answer_3' => 'sunday',
	'anti_spam_explanation' => '(required - to prevent spam)',
	'contactform_required_text' => '(required)',
	'contactform_yourinformation_text' => 'Your Information:',
	'contactform_name_text' => 'Name',
	'contactform_email_text' => 'Email',
	'contactform_phone_text' => 'Phone Number',
	'contactform_yourmessage_text' => 'Your Message:',
	'contactform_message_text' => 'Message',
	'contactform_submit_text' => 'submit',
	'nav_emaillink_onoff' => 'off',
	'nav_emaillink_text' => 'Email',
	'nav_emaillink_address' => $admin_email,
	'contactform_link_text' => 'Contact',
	'contactform_loading_text' => 'Loading',
	'contact_customfield_required' => 'no',
	'contact_customfield2_required' => 'no',
	'contact_customfield3_required' => 'no',
	'contact_customfield4_required' => 'no',
	'contact_text' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>1846 Woodwind Dr.<br />
Holland, MI, 49423<br />
(616) 857-6309</p>',
	'contactform_ajax' => 'on',
	'contactform_antispam_enable' => 'on',
	
	
	// posting options
	'post_title_link_decoration' => 'none',
	'post_title_link_hover_decoration' => 'underline',
	'post_title_margin_below' => '6',
	'emt_text_transform' => 'uppercase',	
	'emt_font_size' => '11',
	'emb_font_size' => '11',
	'displaytime' => 'no',
	'dateformat' => 'long',
	'cattopbottom' => 'top',
	'catdivider' => ', ',
	'catpreludeinc' => 'yes',
	'catprelude' => 'Posted in ',
	'moretext' => 'View full post &raquo;',
	'indexcontent' => 'full',
	'post_pic_margin_top' => '15',
	'post_pic_margin_bottom' => '15',
	'post_header_align' => 'left',
	'cat_header_placement' => 'same',
	'post_header_border' => 'off',
	'post_header_border_width' => '1',
	'post_header_border_style' => 'solid', 
	'post_header_border_color' => '#cccccc',
	'post_header_border_margin' => '15',
	'post_header_border_padding' => '5',
	'post_divider_onoff' => 'line',
	'post_sep_border_width' => '1',
	'post_sep_border_style' => 'dotted',
	'post_sep_border_color' => '#cccccc',
	'margin_below_post' => '35',
	'padding_below_post' => '40',
	'tagged' => 'Tags:', 
	'tag_sep' => ', ',
	'tags_in_meta' => true,
	'post_header_margin_below' => '25',
	'tags_on_index' => 'yes', 
	'tags_on_single' => 'yes',
	'tags_on_archive' => 'yes', 
	'tags_on_tags' => 'yes',
	'post_pic_margin_top' => '15',
	'post_pic_margin_bottom' => '15',
	
	// comments options
	'emailfriendbody' => 'Have a look at this:',
	'commentsopenclosed' => 'closed',
	'commentslayout' => 'tabbed',
	'commenttime' => 'right',
	'commenttimecolor' => '#cccccc',
	'comments_addacomment_text' => 'add a comment',
	'comments_linktothispost_text' => 'link to this post',
	'comments_emailafriend_text' => 'email a friend',
	'comments_minima_show_text' => 'show',
	'comments_minima_hide_text' => 'hide',
	'comments_header_link_font_size' => '13',
	'comments_header_link_font_family' => 'Georgia, Times, serif',
	'comments_comment_bg' => '#ffffff',
	'comments_link_font_size' => '11',
	'comments_link_font_family' => 'Arial, Helvetica, sans-serif',
	'comments_link_font_style' => 'normal',
	'comments_link_decoration' => 'underline',
	'comments_link_hover_decoration' => 'none',
	'comments_comment_border_onoff' => 'off',
	'comments_comment_border_thickness' => '1',
	'comments_comment_border_color' => '#cccccc',
	'comments_comment_border_style' => 'dotted',
	'comments_moderation_text' => '(Your comment is awaiting moderation)',
	'comments_moderation_style' => 'italic',
	'comments_linktothispost' => 'yes',
	'comments_emailafriend' => 'yes',
	'comments_emailafriend_subject' => get_bloginfo( 'name', 'display' ),
	'boxy_comments_line_color' => "#cccccc",
	'comment_author_link_blank' => "",
	
	
	// archive, category, tag, search, author
	'archivecontent' => 'excerpt',
	'archive_h2_font_size' => '19', 
	'archive_h2_font_color' => '#666666',
	'archive_h2_font_style' => 'normal',
	'archive_h2_margin_below' => '30',
	'archive_comments' => 'off',
	'archive_comments_showhide' => 'hide',
	'archive_post_divider' => 'same',
	'archive_content_option' => 'excerpt',
	'archive_content' => 'full',
	'category_content' => 'full',
	
	
	// footer options
	'footer_include' => 'yes',
	'footer_bg_color' => '#232323',
	'footer_headings_font_family' => 'Arial, Helvetica, sans-serif',
	'footer_headings_font_color' => '#ffffff',
	'footer_headings_font_size' => '17',
	'footer_headings_margin_below' => '10',
	'footer_headings_font_style' => 'normal',
	'footer_link_font_size' => '13',
	'footer_widget_margin_below' => '30',
	'footer_subscribebyemail' => 'off',
	'footer_subscribebyemail_placement' => 'left',
	'footer_subscribebyemail_header' => 'Subscribe by email',
	'footer_subscribebyemail_note' => 'enter your email address to receive notification via email whenever there is a new post.',
	'footer_subscribebyemail_submit' => 'subscribe',

	
	
	
	// advanced options
	'lazyloader' => 'on',
	'audioplayer' => 'off',
	'audioplayer_autostart' => 'yes',
	'audioplayer_loop' => 'yes',
	'audioplayer_center_bg'=> '#f8f8f8',
	'audioplayer_text'  => '#666666',
	'audioplayer_left_bg' => '#eeeeee',
	'audioplayer_left_icon'=> '#666666',
	'audioplayer_right_bg'=> '#cccccc',
	'audioplayer_right_icon'=> '#666666',
	'audioplayer_right_bg_hover'=> '#999999',
	'audioplayer_right_icon_hover'=> '#ffffff',
	'audioplayer_slider'=> '#666666',
	'audioplayer_loader'=> '#9FFFB8',
	'audioplayer_track'=> '#ffffff',
	'audioplayer_track_border'=> '#666666',
	'audio_on_home' => 'yes',
	'audio_on_single' => 'no',
	'audio_on_pages' => 'no',
	'audio_on_archive' => 'no',
	'audio_hidden' => 'off',
	'sponsors' => 'off',
	'sponsors_side_margins' => '70',
	'sponsors_img_margin_right' => '15',
	'sponsors_img_margin_below' => '20',
	'sponsors_border_color' => '#cccccc',
	'nav_previous' => '&laquo; Older posts',
	'nav_next' => 'Newer posts &raquo;',
	'nav_previous_align' => 'left',
	'nav_next_align' => 'right',
	'blog_width' => '994',
	'inner_margin' => '30',
	'allow_remote_support' => 'off',
	'override_css_switch' => 'off',
	'override_css' => '/* user-generated custom CSS rules */',
	'show_hidden' => 'hide',
	'custom_js_switch' => 'off',
	'no_right_click' => '',
	'no_left_click' => 'on',
	'maintenance_message' => 'This blog is temporarily unavailable while customizations are being made.  Please check back soon.  Thanks for your patience!',
	'maintenance_mode' => 'off',
	'pathfixer' => 'off',
	
	// translation
	'translate_by' => 'by',
	'translate_switch' => 'off',
	'translate_commentform_message' => 'Your email is <em>never</em> published or shared.',
	'translate_comments' => 'comments',
	'translate_comment' => 'comment',
	'translate_no' => 'no',
	'translate_comments_required' => 'Required fields are marked',
	'translate_comments_name' => 'Name',
	'translate_comments_email' => 'Email',
	'translate_comments_website' => 'Website',
	'translate_comments_comment' => 'Comment',
	'translate_comments_button' => 'Post Comment',
	'translate_search_notfound_header' => 'Nothing found',
	'translate_search_notfound_text' => 'Sorry, but nothing matched your search criteria. Please try again with some different keywords.',
	'translate_search_results' => 'Search Results for:',
	'translate_search_notfound_button' => 'Find',
	'translate_archives_monthly' => 'Monthly Archives:',
	'translate_archives_yearly' => 'Yearly Archives:',
	'translate_blog_archives' => 'Blog Archives',
	'translate_tag_archives' => 'Tag Archives:',
	'translate_category_archives' => 'Category Archives:',
	'translate_author_archives' => 'Author Archives:',
	'translate_404_header' => 'Not Found',
	'translate_404_text' => 'Apologies, but we were unable to find what you were looking for. Perhaps searching will help.',
);


// Default images
$p2['defaultimages'] = array(
	'logo' => 'logo.jpg',
	'flashheader1' => 'default-header1.jpg',
	'flashheader2' => 'nodefaultimage.gif',
	'flashheader3' => 'nodefaultimage.gif',
	'flashheader4' => 'nodefaultimage.gif',
	'flashheader5' => 'nodefaultimage.gif',
	'flashheader6' => 'nodefaultimage.gif',
	'flashheader7' => 'nodefaultimage.gif',
	'flashheader8' => 'nodefaultimage.gif',
	'flashheader9' => 'nodefaultimage.gif',
	'flashheader10' => 'nodefaultimage.gif',
	'flashheader11' => 'nodefaultimage.gif',
	'flashheader12' => 'nodefaultimage.gif',
	'flashheader13' => 'nodefaultimage.gif',
	'flashheader14' => 'nodefaultimage.gif',
	'flashheader15' => 'nodefaultimage.gif',
	'flashheader16' => 'nodefaultimage.gif',
	'flashheader17' => 'nodefaultimage.gif',
	'flashheader18' => 'nodefaultimage.gif',
	'flashheader19' => 'nodefaultimage.gif',
	'flashheader20' => 'nodefaultimage.gif',
	'flashheader21' => 'nodefaultimage.gif',
	'flashheader22' => 'nodefaultimage.gif',
	'flashheader23' => 'nodefaultimage.gif',
	'flashheader24' => 'nodefaultimage.gif',
	'flashheader25' => 'nodefaultimage.gif',
	'flashheader26' => 'nodefaultimage.gif',
	'flashheader27' => 'nodefaultimage.gif',
	'flashheader28' => 'nodefaultimage.gif',
	'flashheader29' => 'nodefaultimage.gif',
	'flashheader30' => 'nodefaultimage.gif',
	'post_sep' => 'nodefaultimage.gif',
	'blog_bg' => 'nodefaultimage.gif',
	'iphone_webclip_icon' => 'nodefaultimage.gif',
	'bio_separator' => 'nodefaultimage.gif',
	'biopic1' => 'biopic.jpg',
	'biopic2' => 'nodefaultimage.gif',
	'biopic3' => 'nodefaultimage.gif',
	'biopic4' => 'nodefaultimage.gif',
	'biopic5' => 'nodefaultimage.gif',
	'biopic6' => 'nodefaultimage.gif',
	'biopic7' => 'nodefaultimage.gif',
	'biopic8' => 'nodefaultimage.gif',
	'biopic9' => 'nodefaultimage.gif',
	'biopic10' => 'nodefaultimage.gif',
	'biopic11' => 'nodefaultimage.gif',
	'biopic12' => 'nodefaultimage.gif',
	'biopic13' => 'nodefaultimage.gif',
	'biopic14' => 'nodefaultimage.gif',
	'biopic15' => 'nodefaultimage.gif',
	'bio_signature' => 'nodefaultimage.gif',
	'lazyloader' => 'nodefaultimage.gif',
	'banner1' => 'nodefaultimage.gif',
	'banner2' => 'nodefaultimage.gif',
	'banner3' => 'nodefaultimage.gif',
	'banner4' => 'nodefaultimage.gif',
	'banner5' => 'nodefaultimage.gif',
	'banner6' => 'nodefaultimage.gif',
	'banner7' => 'nodefaultimage.gif',
	'banner8' => 'nodefaultimage.gif',
	'banner9' => 'nodefaultimage.gif',
	'banner10' => 'nodefaultimage.gif',
	'banner11' => 'nodefaultimage.gif',
	'banner12' => 'nodefaultimage.gif',
	'banner13' => 'nodefaultimage.gif',
	'banner14' => 'nodefaultimage.gif',
	'banner15' => 'nodefaultimage.gif',
);

// array of files
$p2['miscfiles'] = array(
	'favicon' => true,
	'audio1' => true,
	'audio2' => true,
	'audio3' => true,
	'audio4' => true,
);

// Image size requirements.  can do W & H or just one
$p2['recommendations'] = array(
	'reco' => array('width' => '397', 'height' => '108'),
	'iphone_webclip_icon' => array('width' => '57', 'height' => '57'),
	'banner1' => array('height' => '100', 'width' => '155'),
	'banner2' => array('height' => '100', 'width' => '155'),
	'banner3' => array('height' => '100', 'width' => '155'),
	'banner4' => array('height' => '100', 'width' => '155'),
	'banner5' => array('height' => '100', 'width' => '155'),
	'banner6' => array('height' => '100', 'width' => '155'),
	'banner7' => array('height' => '100', 'width' => '155'),
	'banner8' => array('height' => '100', 'width' => '155'),
	'banner9' => array('height' => '100', 'width' => '155'),
	'banner10' => array('height' => '100', 'width' => '155'),
	'banner11' => array('height' => '100', 'width' => '155'),
	'banner12' => array('height' => '100', 'width' => '155'),
	'banner13' => array('height' => '100', 'width' => '155'),
	'banner14' => array('height' => '100', 'width' => '155'),
	'banner15' => array('height' => '100', 'width' => '155'),
	'favicon' => array('height' => '16', 'width' => '16')
);


$p2['staticfiles'] = array(
	'css' => array('dynamic' => 'dynamic/customstyle.css.php', 'static' => 'custom.css'),
	'js' => array('dynamic' => 'dynamic/themescript.js.php', 'static' => 'themescript.js'),
	'xml' => array('dynamic' => 'dynamic/images.xml.php', 'static' => 'images.xml'),
	'htc' => array('dynamic' => 'dynamic/pngHack.htc.php', 'static' => 'pngHack.htc'),
	'preview' => array('dynamic' => 'dynamic/preview.css.php', 'static' => 'preview.css'),
	'empty' => array('dynamic' => 'dynamic/empty.php', 'static' => 'empty.html') // Dummy empty file just forcing a content-type:text/html header
);



/* Messages used in various functions */
$p2['msg'] = array(

	/**** Upload process ****/
	'reset_link' => 'Reset Image',
	'file_upload_ok' => 'File uploaded',
	'reset_form_title' => 'Reset this file to default?',
	'reset_form_button' => 'Reset',
	'file_reset_ok' => 'File reverted to default',
	'no_file_uploaded' => 'No file uploaded.',
	'file_too_big' => 'File is too big (max: 750k)',
	'generic_error' => 'Something went wrong',
	'file_partial_upload' => 'File partially uploaded',
	'image_not_found' => 'No default image for this option.',
	'try_again' => 'Please <a href="%s">try again</a>',
	// webserver wide config problem. Shouldn't happen.
	'no_temp_folder' => 'Critical: Missing a temporary folder. Your webserver will not accept any upload!',
	// webserver wide config problem. Shouldn't happen. 
	'upload_write_error' => 'Failed to write file to disk while uploading. Your webserver will not accept any upload!', 
	/**** General option page ****/
	'pick_color' => 'Pick a Color',

);

/* used by p2_font_option_addclass() function to add classes to font/link option groups */
$preview_options['name'] = array( 
	'_font_family',
	'_link_visited_font_color',
	'_font_size',
	'_font_style',
	'_link_decoration',
	'_link_hover_decoration',
	'_text_transform',
	'_nonlink_font_color',
	'_link_hover_font_color',
	'_font_weight',
	'_font_color',
);
$preview_options['class'] = array( 
	' font-family-select',
	' visited-link-font-color-picker',
	' font-size-input',
	' font-style-select',
	' link-decoration-select',
	' link-hover-decoration-select',
	' text-transform-select',
	' nonlink-font-color-picker',
	' link-hover-font-color-picker',
	' font-weight-select',
	' font-color-picker',
);
$loremsmall = 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.';
$lorem = '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>';
$alt_comments = '<div style="height:1.6em;"><span style="float:left;"><a class="unvisited">Mike</a> - Great shots! &nbsp;&nbsp;</span><span id="comment-timestamp">May 1, 2008 - 9:53 am</span></div><div style="height:1.6em;" class="alt"><span style="float:left;"><a class="unvisited">Joe</a> - Love them! &nbsp;&nbsp;</span><span id="comment-timestamp">May 1, 2008 - 9:53 am</span></div><div style="height:1.6em;"><span style="float:left;"><a class="unvisited">Fred</a> - Nice Work! &nbsp;&nbsp;</span><span id="comment-timestamp">May 1, 2008 - 9:53 am</span></div><div style="height:1.6em;" class="alt"><span style="float:left;"><a class="unvisited">Susy</a> - Keep it real! &nbsp;&nbsp;</span><span id="comment-timestamp">May 1, 2008 - 9:53 am</span></div>';
$preview_options['preview'] = array( 
	'gen_font_family' => $loremsmall,
	'gen_link_font_color' => '<a class="unvisited">A sample link</a>&nbsp; &nbsp;<a class="visited">A visited link</a>',
	'header_font_family' => 'A Sample Headline',
	'nav_bg_color' => '<ul><li><a class="unvisited title">Menu Dropdown Title</a></li><li><a class="unvisited withhover">Dropdown Link 1</a></li><li><a class="unvisited withhover">Dropdown Link 2</a></li><li id="vis-menu"><a class="visited withhover">Visited Dropdown Link</a></li></ul>',
	'bio_header_font_family' => 'Welcome to my blog!',
	'bio_para_font_family' => $lorem,
	'post_title_link_font_size' => '<a class="unvisited">A Sample Post Title</a><a style="height:25px;display:block;" class="visited"></a><a class="visited">A Visited Post Title</a>',
	'post_text_font_family' => $lorem,
	'emt_font_family' => 'Thursday, February 23, 2009 &nbsp;&nbsp; Posted in...',
	'emb_font_family' => 'Tags: ... Posted in...',
	'em_link_font_color' => '<a class="unvisited">Weddings,</a> <a class="unvisited">Portraits,</a> <a class="unvisited">Personal</a> &nbsp;&nbsp;&nbsp;<a class="visited">Visited link</a>',
	'archive_h2_font_family' => 'Monthly Archives: February 2009',
	'single_h1_font_family' => 'A Sample Post Title',
	'comments_header_link_font_size' => 'by <a class="unvisited">Jane</a> &nbsp;&nbsp; <a class="unvisited">11 comments</a>',
	'comments_link_font_size' => '<div style="height:1.6em;"><span style="float:left;"><a class="unvisited">Mike</a> - Great shots! &nbsp;&nbsp;</span><span id="comment-timestamp">May 1, 2008 - 9:53 am</span></div>',
	'footer_headings_font_family' => 'Archives',
	'footer_link_font_size' => '<a class="unvisited" style="display:block;">February 2009</a><a class="unvisited" style="display:block;">March 2009</a><a class="unvisited" style="display:block;">April 2009</a><span style="display:block;">A bit of non-link text</span><a class="visited" style="display:block;">Visited Footer Link</a>',
	'nav_below_link_font_size' => '<a class=
	"unvisited">&laquo; Older Posts</a> &nbsp;&nbsp;&nbsp;&nbsp; <a class="unvisited">Newer Posts &raquo;</a><a class="visited" style="display:block;height:15px"><a class="visited">&laquo; Older Posts (visited)</a> &nbsp;&nbsp;&nbsp;&nbsp; <a class="visited">Newer Posts (visited) &raquo;</a>',
);

?>